- src/Mapbender/CoreBundle/Resources/translations/messages.ru.xlf
I translated corebundle translation for Russian language
> - core ru translation

- src/Mapbender/MobileBundle/Resources/public/sass/theme/mobile.scss
> Fix mobile icons #311

- src/Mapbender/CoreBundle/Resources/views/index.html.twig
- src/Mapbender/MobileBundle/Resources/views/Template/mobile.html.twig
> Add default scale factor variable for mobile template.

- src/Mapbender/CoreBundle/Resources/public/sass/theme/mapbender3.scss
> Add smooth image transition effect by loading.

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js
Use watchPosition instead of requesting standalone with timeout / interval.
> CP#5164: GPS accuracy fix

- src/Mapbender/PrintBundle/Component/ImageExportService.php
- src/Mapbender/PrintBundle/Resources/public/mapbender.element.imageExport.js
ImageExport opacity fix
some code cleaning
> imageexport: fixed opacity

- src/Mapbender/CoreBundle/Element/Map.php
Fixed XSS vulnerability at map element / POI feature.
> fix XSS vulnerability

- src/Mapbender/WmsBundle/Resources/views/Repository/form.html.twig
Enhanced workaround for chrome based browsers.
> An other workaround to disable autocomplete password (add wms source)

- src/Mapbender/ManagerBundle/Resources/views/Repository/index.html.twig
No need to check datasource yet
> No need to check datasource yet

- src/Mapbender/CoreBundle/Resources/public/sass/element/printclient.scss
* labelinput is too small with 80px
* like for searchrouter width was set to auto
> Update printclient.scss changed width to auto to support long titles

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js
#6091 Improvements GPS Position. Center on First Position and Zoom to accuracy on First Position gefixt.
> gps first position and center on first you know what I mean. #6091

- src/Mapbender/ManagerBundle/Controller/ApplicationController.php
please check.
-- 
send from my FOSS4G CodeSprint
> icon visibility of application in configuration #7082

- src/Mapbender/WmcBundle/Resources/public/mapbender.element.wmclist.js
> fixed wmclist part of vulnerability

- src/Mapbender/CoreBundle/Element/Type/TargetElementType.php
> added empty button target to dropdown

- src/Mapbender/CoreBundle/Resources/views/Element/featureinfo.html.twig
> fixed featureinfo css in certain conditions

- src/Mapbender/CoreBundle/Resources/public/mapbender.model.js
> fixed app loading when layersets were deleted

- src/Mapbender/CoreBundle/Resources/public/sass/element/featureinfo.scss
fixes regression introduced by last 'fix'
> Fixed css regression

- src/Mapbender/CoreBundle/Element/Map.php
Upon change request #5791 i changed default tilesize to 512
> change tilesize default to 512

- src/Mapbender/CoreBundle/Component/SecurityContext.php
@eSlider Please add this commit since https://github.com/mapbender/search/commit/b040214d7f10bdd5540b311378634cf567533365 depends on it. Thx.
> Add anonymous user constant for security.

- src/Mapbender/PrintBundle/Component/OdgParser.php
- src/Mapbender/PrintBundle/Component/PrintService.php
another small print fix. needed for wrong configured templates.
> printservice style fix

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.printClient.js
If layers have a changed visibility when printing on certain scales, the
corresponding styles parameter has to be updated, too.
> fixed printing on some scales

- src/Mapbender/CoreBundle/Resources/public/mapbender.model.js
Fixes duplicate loads of WMS when a layer is going out of scale.
Fixed internal issue 7689.
> fix duplicate loads of WMS

- src/Mapbender/PrintBundle/Component/PrintService.php
* see Tickets #476 #477
* see also changes in mapbender-starter
> legendpage_image and logo on legend page #476 #477

- src/Mapbender/CoreBundle/Resources/translations/messages.en.yml
> fixed typos in core bundle translation see #498

- src/Mapbender/CoreBundle/Resources/views/Element/search_router.html.twig
* see https://github.com/mapbender/mapbender/issues/488
> SearchRouter in Sidepane move buttons ok/reset under form

- src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.fr.yml
> Restructured translations for de, en and fr in edit/create new application (#510)

- src/Mapbender/WmcBundle/Element/WmcEditor.php
- src/Mapbender/WmcBundle/Resources/public/mapbender.element.wmceditor.js
Mit @eSlider zusammen vom Testserver "Schnelltest" gepusht. Kleine Änderung an den Default-Werten des WMC-Editor für das Frontend. Wir haben das hotfixed und kein Ticket erstellt.
> Add WmcEditor Default Parameters for width and height

- src/Mapbender/CoreBundle/Resources/public/sass/modules/_checkbox.scss
Fixes https://github.com/mapbender/mapbender/issues/528
> fix a css problem with checkboxes by moving it out of screen some more

- src/Mapbender/ManagerBundle/Resources/public/sass/element/form.scss
For better allocation, changed removebutton position to right
> improved position of removebutton

- src/Mapbender/PrintBundle/Component/ImageExportService.php
- src/Mapbender/PrintBundle/Component/PrintService.php
> PrintService/ImageExport: Accept all kinds of image/png from wms

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.ruler.js
and add check if value is set. #538
> Change default value for immediate messurment to null 

- src/Mapbender/CoreBundle/Command/DatabaseUpgradeCommand.php
Command/DatabaseUpgradeCommand.php
will change Configuration.imgPath of each MapElement from "bundles/mapbendercore/mapquery/lib/openlayers/img" to "components/mapquery/lib/openlayers/img"
> Added Command to update old imagepath of map element #530

- src/Mapbender/CoreBundle/Resources/translations/messages.nl.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.nl.yml
- src/Mapbender/PrintBundle/Resources/translations/messages.nl.yml
- src/Mapbender/WmcBundle/Resources/translations/messages.nl.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.nl.yml
These are NL (Dutch) Translations for CoreBundle/ManagerBundle/WmsBundle/WmcBundle/PrintBundle. Applies to issue #557.
> PR for #557 - Hotfix/translations branch - NL (Dutch) Translations 

- src/Mapbender/CoreBundle/Resources/translations/messages.tr.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.tr.yml
* core bundle tr file was cleaned, yaml was not valid
* replaced ' in the text to ´ 
* deleted the rows #---------------------
* comments in one row after translated textes
> created valid YML, erased - lines, comments in one line

- src/Mapbender/PrintBundle/Component/PrintService.php
Fixes print error in app_dev on windows systems with php 7.1
> PrintService: type conversion for fontsize value

- src/Mapbender/CoreBundle/Element/Map.php
See https://github.com/mapbender/mapbender/issues/642
> Add isset call for poi[srs] check to avoid acces on undefined index

- CHANGELOG.md
- src/Mapbender/CoreBundle/Component/InstanceConfigurationOptions.php
- src/Mapbender/CoreBundle/Controller/ApplicationController.php
- src/Mapbender/WmcBundle/Component/WmcParser110.php
- src/Mapbender/WmsBundle/Component/Style.php
- src/Mapbender/WmsBundle/Component/WmsInstanceConfiguration.php
- src/Mapbender/WmsBundle/Component/WmsInstanceEntityHandler.php
- src/Mapbender/WmsBundle/Component/WmsInstanceLayerEntityHandler.php
- src/Mapbender/WmsBundle/Element/WmsLoader.php
- src/Mapbender/WmsBundle/Entity/WmsInstanceLayer.php
- src/Mapbender/WmsBundle/Entity/WmsLayerSource.php
- src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js
GetLegendGraphic for protected WMS now uses the same path in instanceTunnelAction as GetMap / GetFeatureInfo. "Special" bypass for legend urls has been removed.
> Fix tunnel getlegendgraphic

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.scaleselector.js
* Fix displaying scale value in scale selector
* Clean scaleselector element JS code
Closes: #647
Associated: #595
> Fix displaying scale value in scale selector

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.legend.js
- src/Mapbender/CoreBundle/Resources/views/Element/legend.html.twig
Legend image refactored and improved:
* Split code in logical parts (methods)
* Removed unnecessary repeated code
* Added method documentation
* Images loaded first if requiered, not all at once
* Every time render completely new HTML, also if map layers visibility changed
* Add simple progress loader (spinner) this will displayed in HTML container before images was loaded  
* Fixed open/close/ready event handling (callbacks)
* Fixed posible inline HTML XSS 
* Using jQuery instead of String-HTML concatination
* Render HTML only first if Map is ready
> Refactor legend image element

- src/Mapbender/CoreBundle/Component/Application.php
- src/Mapbender/CoreBundle/Resources/public/mapbender.container.info.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.aboutDialog.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.activityindicator.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.base.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.button.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.coordinatesdisplay.js
- src/Mapbender/CoreBundle/Resources/public/polyfills.js
Done the task #635: refactoring of the following elements:
- AboutDialog
- ActivityIndicator
- BaseSourceSwitcher
- Button
- CoordinatesDisplay
Added the base element.
> JS-Review form Happy Friday

- src/Mapbender/CoreBundle/Component/SecurityContext.php
This is the mapbender-side fix to issue #713.
We observed a regression around commit 3353075d2c222c2e13f36ff29e3193b455b41edc that enabled a logged-in user with no particular rights (non-root definitely) to successfully create new applications.
I assume the old change was to also support calls to SecurityContext::isUserAllowedToCreate with class name string arguments (as seen [in ExchangeHandler](https://github.com/mapbender/mapbender/blob/e7ee068eb8c494683bb71fc39937f0766df710bf/src/Mapbender/ManagerBundle/Component/ExchangeHandler.php#L96)).
This pull attempts to "normalize" the argument into an ObjectIdentity before forwarding to isGranted. Only the create action check has been touched. For creation, it seems safe to assume a "class" type OI is required because the check has no bearing …
> Fix false-positive result in SecurityContext::isUserAllowedToCreate(new Application)

- composer.json
> Change namespace of vis-ui

- src/Mapbender/ManagerBundle/Controller/ElementController.php
- src/Mapbender/ManagerBundle/Resources/public/js/application-edit.js
- src/Mapbender/ManagerBundle/Resources/public/sass/element/form.scss
- src/Mapbender/ManagerBundle/Resources/views/translations.json.twig
The html code of an element edit form will be updated after submit using response. All error messages will be shown. Fixes #734
> Update element form after submit 

- src/Mapbender/ManagerBundle/Resources/public/js/application-edit.js
- src/Mapbender/ManagerBundle/Resources/public/sass/manager/manager.scss
Fixed comments from the review https://github.com/mapbender/mapbender/pull/735#pullrequestreview-94707821. Relates to the issue #734
> Clean the code of the elementFormSubmit function

- CHANGELOG.md
- src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.es.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.fr.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.it.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.nl.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.pt.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.ru.yml
- src/Mapbender/ManagerBundle/Resources/views/Element/select.html.twig
* see ticket #612 : backend - add filter in add element dialog 
* used same technique like for fltering source, layersets, services
* added code and translation
> backend - add filter in add element dialog

- CHANGELOG.md
- src/Mapbender/CoreBundle/Component/SourceMetadata.php
- src/Mapbender/WmsBundle/Component/WmsMetadata.php
* see ticket #742 
Enhancement for WMS Metadata Dialog: 
* blank between title and instance title
* do not show WMS Title only show WMS Instance Title when the same text
> metadata dialog wms title blank #742

- src/Mapbender/CoreBundle/Resources/public/mapbender.application.js
> Remove debug mode and app initialization without error handling

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.searchRouter.js
* SearchRouter: Add highlight feature on map when hover (mouseover) over searchresult
* refers to ticket #730 
* adds new styleMap -> temporary (see OL2 documentation http://docs.openlayers.org/library/feature_styling.html)
For documentation:
en
`For styleMap you can define a temporary section. Temporary is used while sketching a feature.`
de
`In der Konfiguration kommt nun zusätzlich ein Block temporary hinzu. Über temporary kann die mouseover-Farbe gesetzt werden.`
```
styleMap:
default:
strokeColor: '#00ff00'
fillColor: '#00ff00'
strokeOpacity: 1
fillOpacity: 1
select:
strokeColor: '#ff00ff'
fillColor: '#ff00ff'
fillOpacity: 1
temporary:
strokeColor: '#0000ff'
fillColor: '#0000ff'
fillOpacity: 1
```
> SearchRouter: Feature/search router hover highlighter

- src/Mapbender/CoreBundle/Component/XmlValidator.php
- src/Mapbender/WmsBundle/Element/WmsLoader.php
- src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js
- src/Mapbender/WmsBundle/Resources/translations/messages.de.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.en.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.es.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.fr.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.it.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.nl.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.pt.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.ru.yml
- src/Mapbender/WmsBundle/Resources/views/Element/wmsloader.html.twig
The WmsInstanceHandler was generating double configurations which was preventing the frontend from loading the wms. This is now fixed.
This fixes #818
> Fix wms loader not loading wms

- src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js
https://github.com/mapbender/mapbender/issues/830
> Raise maxFeatures to 1000

- src/Mapbender/CoreBundle/Resources/views/cookieconsent.html.twig
- src/Mapbender/CoreBundle/Resources/views/index.html.twig
Needs additional pull from starter
https://github.com/mapbender/mapbender/issues/834
> Add cookieconsent code for mapbender

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.sketch.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.model.ol4.js
Ol4 sketch sketch refactured and in ol4 style now
> Ol4 sketch

- src/Mapbender/CoreBundle/Resources/public/mapbender.application.js
Ticket https://github.com/mapbender/mapbender/issues/933
new Funktion defined and used for getting the parameters of an url (instead of using OpenLayers.Util.getParameters)
> mew Mapbender Util Funktion to get the url parameters

- src/Mapbender/CoreBundle/Resources/public/mapbender.model.ol4.js
- src/Mapbender/PrintBundle/Resources/public/mapbender.element.imageExport.js
basic imageExport functionality done and some new functions in the model.
> basic imageExport functionality

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.coordinatesdisplay.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.model.ol4.js
- Coordinates Display ol4 implementation
- Funktion` createMousePositionControl()` in Mapbender.Model hinzugefügt
- Braucht noch Finetuning: z.B. evtl. CSS-Formatierung der Koordinatenangabe
- noch nicht ausreichend implementiert und getestet für Darstellung der Koordinaten in der Karte an verschiedenen positionen (right-top, left-top, etc.)
- funktioniert aber erstmal prinzipiell
> Coordinates Display ol4 implementation

- src/Mapbender/CoreBundle/Element/SimpleSearch.php
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.simplesearch.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.model.ol4.js
> Ol4 fix/simple search

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js
https://github.com/mapbender/mapbender/issues/958
https://github.com/mapbender/mapbender/issues/915
> Fix overview wrong extent

- src/Mapbender/CoreBundle/Resources/public/init/projection.js
- src/Mapbender/CoreBundle/Resources/public/mapbender-model/mapbender.model.mappopup.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js
- src/Mapbender/CoreBundle/Resources/public/sass/modules/mapPopup.scss
> Update POI initialization on a map

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.redlining.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.scaledisplay.js
> Fix Javascript constructs incompatible with certain IE versions

- src/Mapbender/CoreBundle/Resources/translations/messages.it.yml
* improved italian translation
* see #1044
* internal Ticket 680
> Ticket 1044: [translations] add missing Italian translations

- src/Mapbender/CoreBundle/Element/PrintClient.php
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.printClient.js
- src/Mapbender/CoreBundle/Resources/translations/messages.de.yml
- src/Mapbender/CoreBundle/Resources/translations/messages.en.yml
- src/Mapbender/CoreBundle/Resources/views/Element/printclient.json.twig
Digitizer print scale made configurable.
Changes can be merged into master branch as well.
> digitizer print scale made configurable

- src/Mapbender/CoreBundle/Resources/translations/messages.it.yml
- src/Mapbender/KmlBundle/Resources/translations/messages.it.yml
- src/Mapbender/ManagerBundle/Resources/translations/messages.it.yml
- src/Mapbender/PrintBundle/Resources/translations/messages.it.yml
- src/Mapbender/WmcBundle/Resources/translations/messages.it.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.en.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.it.yml
All italian files are traslated
> #1044 add missing Italian translations

- src/Mapbender/PrintBundle/Element/PrintClient.php
Now you can use different and multiple replacement patterns.
> fix addReplacePattern Function

- src/Mapbender/MobileBundle/Resources/public/sass/theme/mobile.scss
* Reported bug from David Müller via Mailing-list
* https://lists.osgeo.org/pipermail/mapbender_users/2018-November/005522.html
> fix MobileTemplate FeatureInfo scrollable

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.redlining.js
Closes #1133 
Collateral: resolves double-creation of tool on every activation click, observed in debugging.
> Redlining: Allow direct disabling of current tool via second click on tool button

- src/Mapbender/CoreBundle/Controller/LoginController.php
- src/Mapbender/CoreBundle/Form/Type/LoginType.php
- src/Mapbender/CoreBundle/Resources/translations/messages.de.yml
- src/Mapbender/CoreBundle/Resources/translations/messages.fr.yml
- src/Mapbender/CoreBundle/Resources/translations/messages.it.yml
- src/Mapbender/CoreBundle/Resources/translations/messages.nl.yml
- src/Mapbender/CoreBundle/Resources/translations/messages.ru.yml
- src/Mapbender/CoreBundle/Resources/views/Login/login.html.twig
* error.message is Bad credentials.
* added . to enable translation
> changed to Bad credentials. with .

- src/Mapbender/CoreBundle/Component/ApplicationYAMLMapper.php
Setter for engine code in YAML applications. I hope this is the correct target branch.
> Setter for engine code in YAML applications

- src/Mapbender/CoreBundle/Component/KeywordUpdater.php
- src/Mapbender/WmsBundle/Component/Wms/Importer.php
> remove no longer needed entities

- src/Mapbender/CoreBundle/Resources/public/mapbender.model.ol4.js
* Fix not printing circles 
* Fix not respecting icon scale in print
> Fix for wrong icon scale and not printing circle features

- src/Mapbender/WmsBundle/Component/WmsMetadata.php
- src/Mapbender/WmsBundle/Resources/translations/messages.de.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.en.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.es.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.fr.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.it.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.nl.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.pt.yml
- src/Mapbender/WmsBundle/Resources/translations/messages.ru.yml
- add missing translation for abstract
- fetch metadata information
- see ticket #1256
> Layertree add Abstract for Layers in metadata dialog

- src/Mapbender/CoreBundle/Command/DatabaseUpgradeCommand.php
* updated help text for app/console mapbender:database:upgrade --help
* typo and deleted version
* see ticket https://github.com/mapbender/mapbender/issues/1260
> Update help for command mapbender:database:upgrade

- src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js
Extends [Mapbender "declarative" WmsLoader links](https://doc.mapbender.org/en/functions/misc/wms_loader.html#how-to-add-a-wms-by-defining-a-link), i.e. links in prepared HTML markup with `mb-action="source.add.wms"`.
Added Wms source can now receive additional custom GetMap query parameters defined via the link's `mb-add-vendor-specific` attribute, which should contain query string formatted parameter assignments.
For example, one might place an HTML element into a toolbar containing the following markup:
```html
<a mb-action="source.add.wms"
mb-wms-layers="krankenhaus" 
mb-add-vendor-specific="extra-param=custom-value&amp;another-extra-param=A%3AB%3AC"
href="https://www.wms.nrw.de/wms/krankenhaus?VERSION=1.3.0">Add source</a>
```
When clicking on this link, the new Wms source will be …
> Support adding custom wms params via new mb-action link attribute mb-add-vendor-specific

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.searchRouter.js
- src/Mapbender/CoreBundle/Resources/public/sass/modules/_dropdown.scss
- src/Mapbender/CoreBundle/Resources/views/Element/search_router.html.twig
- src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js
- src/Mapbender/WmsBundle/Resources/views/Element/wmsloader.html.twig
in Search Router and WMSLoader
refs #1276
> Fix missing visual feedback when submitting invalid form

- src/Mapbender/CoreBundle/Resources/translations/messages.de.yml
stop_drawing: Zeichnen unterbrechen instead of Zeichnen stoppen, as you only pause the drawing and can continue
>  sketch translation suggestion: stop_drawing: Zeichnen unterbrechen

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.searchRouter.js
> [SearchRouter] Zoom to feature automatically if there is only one result

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.scaleselector.js
> Zoom in application did not work when fixed zoom steps were active

- CHANGELOG.md
- src/Mapbender/CoreBundle/Component/SQLSearchEngine.php
fixes  #1474
Regression introduced in https://github.com/mapbender/mapbender/commit/1a1aeec58604c47e23ae98b5162713bd0cd46a09
> [SearchRouter] Fix additional search properties were ignored

- CHANGELOG.md
- src/Mapbender/WmsBundle/Component/Wms/SourceInstanceFactory.php
- src/Mapbender/WmsBundle/Entity/WmsInstanceLayer.php
> Correctly handle removal of GetFeatureInfo capability when refreshing sources

- src/Mapbender/CoreBundle/Resources/public/sass/modules/_base.scss
set cursor:pointer when hovering "intance on/off" or "delete" in application backend
> adjust cursor layout in application backend

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.simplesearch.js
> [Simple Search] Check if locally stored configuration exist and fallback to 0 if not

- src/Mapbender/CoreBundle/Command/ConfigCheckCommand.php
- paths fixed
- still open issue to check php version and delete php7 infos
> bin/console mapbender:config:check fixed file paths

- src/FOM/UserBundle/Component/FOMIdentitiesProvider.php
- src/FOM/UserBundle/Entity/User.php
- src/FOM/UserBundle/Form/Type/UserType.php
- src/Mapbender/CoreBundle/Entity/Application.php
- src/Mapbender/ManagerBundle/Controller/ApplicationExchangeController.php
- src/Mapbender/ManagerBundle/Resources/public/components.js
- src/Mapbender/PrintBundle/Component/Plugin/PrintQueuePlugin.php
- src/Mapbender/WmsBundle/Component/Wms/SourceInstanceFactory.php
fixes 
- error when adding or editing users
- error when editing security settings for an application 
- ajax error when adding to print queue
> Fix remaining old class references

- src/Mapbender/CoreBundle/Component/IconPackageFa4.php
> Update IconPackageFa4.php iconEarth fas fa-earth-africa instead of far

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js
- src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml
- src/Mapbender/WmsBundle/Resources/views/frontend/instance.html.twig
Tabs in the feature info window are now sorted in the order they appear in the layer tree.
> Order FeatureInfo tabs

- src/Mapbender/CoreBundle/Resources/public/sass/theme/mapbender3.scss
> Wrap overly long rows in metadata dialog

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.searchRouter.js
- adds labeling possibility to searchrouter
- similar to digitizer you can define a label definition in the configuration
```
styleMap:
default:
strokeColor: '#8000FF'
strokeWidth: 5
strokeOpacity: 1
fillColor: '#8000FF'
fillOpacity: 0.8
fillWidth: 6
label: ${name}
fontColor: "#000000"
fontSize: 10px
fontFamily: 'Arial, Courier New, monospace'
fontWeight: bold
labelOutlineColor: '#ffffff'
labelOutlineWidth: 1
labelYOffset: -18
labelXOffset: -18
select:
strokeColor: '#ff00ff'
strokeWidth: 6
strokeOpacity: 1
fillColor: '#ff00ff'
fillOpacity: 0.6
fillWidth: 12
label: ${name} - ${gid}
fontColor: "#ff00ff"
fontSize: 15px
fontFamily: 'Arial, Courier New, monospace'
fontWeight: bold
labelOutlineColor: '#ffff00'
labelOutlineWidth: 1
labelYOffset: 18
labelXOffset: 18
temporary:
strokeColor: …
```
> SearchRouter add possibility to label results

- CHANGELOG.md
- src/Mapbender/CoreBundle/Component/IconPackageFa4.php
- src/Mapbender/CoreBundle/Element/DataUpload.php
- src/Mapbender/CoreBundle/Element/Type/DataUploadAdminType.php
- src/Mapbender/CoreBundle/Resources/config/elements.xml
- src/Mapbender/CoreBundle/Resources/config/services.xml
- src/Mapbender/CoreBundle/Resources/public/element/dataupload.js
- src/Mapbender/CoreBundle/Resources/public/element/dataupload.scss
- src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml
- src/Mapbender/CoreBundle/Resources/views/Element/dataupload.html.twig
- src/Mapbender/CoreBundle/Resources/views/ElementAdmin/dataupload.html.twig
Added new data upload element for GeoJSON, KML, GML and GPX upload.
> Add new data upload element

- src/FOM/UserBundle/Resources/translations/messages.en.yaml
- delete 3 in Mapbender3 in english version.
> Update messages.en.yaml delete 3 in Mapbender3

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.geosource.js
see https://github.com/mapbender/mapbender/issues/1567
> fix sorting issue in layertree

- src/Mapbender/CoreBundle/Resources/translations/messages.it.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.ru.yaml
> added translation for new element dataupload 

- src/Mapbender/WmtsBundle/Resources/views/Repository/instance-layer-form.html.twig
Fixes the backend form template for WMTS.
The WMTS can then be integrated as a data source again.
However, the WMTS must still be configured as 'activated' when the application is started!
> Fix WMTS form template

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/element/sketch.js
- src/Mapbender/CoreBundle/Resources/public/mapbender-model/StyleUtil.js
- src/Mapbender/CoreBundle/Resources/public/mapbender-model/VectorLayerBridge.js
- src/Mapbender/CoreBundle/Resources/public/mapbender-model/VectorLayerBridgeOl4.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.ruler.js
Previously, a generic blue (OL default) was used while drawing in the sketch tool, only after finishing the drawing process the actual colour was used. Now, the selected colour is already used while drawing the shape.
Also, added convenience method `Mapbender.StyleUtil.createDrawStyle` that is also used by the ruler element.
> [Sketch] Already use selected color while drawing

- src/Mapbender/PrintBundle/Component/PrintService.php
change visibility of createMapImage Method to protected to allow usage in Subclasses
> change visibility of createMapImage from private to protected

- src/Mapbender/ManagerBundle/Resources/public/sass/manager/manager.scss
- backend: reduced padding for icons on application overview. Improved mobile display
> backend: style improvements

- CHANGELOG.md
- src/Mapbender/Utils/ApplicationUtil.php
> Never use a disabled map element

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/element/dataupload.js
> [DataUpload] Fix data type recognition in some browsers / operating systems

- CHANGELOG.md
- src/Mapbender/ManagerBundle/Resources/public/js/application-edit.js
- src/Mapbender/ManagerBundle/Resources/views/Application/form-elements.html.twig
> [Manager] Fix empty region placeholder in layout editor

- src/Mapbender/CoreBundle/Element/Type/FeatureInfoAdminType.php
- src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.es.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.fr.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.it.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.nl.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.pt.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.ru.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.tr.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.uk.yaml
> [FeatureInfo] Add translations for button "print results"

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js
> Allow visiblelayers to activate root layer

- src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapEngineOl4.js
Fixes https://github.com/mapbender/mapbender/issues/1615
> Fix transformation of EPSG:3847 coordinates

- src/FOM/UserBundle/Controller/GroupController.php
- src/FOM/UserBundle/Controller/SecurityController.php
- src/FOM/UserBundle/Controller/UserController.php
- src/FOM/UserBundle/Resources/translations/messages.de.yaml
- src/FOM/UserBundle/Resources/translations/messages.en.yaml
- src/FOM/UserBundle/Resources/translations/messages.es.yaml
- src/FOM/UserBundle/Resources/translations/messages.fr.yaml
- src/FOM/UserBundle/Resources/translations/messages.it.yaml
- src/FOM/UserBundle/Resources/translations/messages.nl.yaml
- src/FOM/UserBundle/Resources/translations/messages.pt.yaml
- src/FOM/UserBundle/Resources/translations/messages.ru.yaml
- src/FOM/UserBundle/Resources/translations/messages.uk.yaml
- src/FOM/UserBundle/Resources/views/Group/list.html.twig
- src/FOM/UserBundle/Resources/views/Permission/list.html.twig
- src/FOM/UserBundle/Resources/views/User/list.html.twig
- src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.es.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.fr.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.it.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.nl.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.pt.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.ru.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.tr.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.uk.yaml
- src/Mapbender/ManagerBundle/Resources/public/components.js
added sort-function for users, usergroups and global authorizations
see internal ticket #7369
> sort-function backend

- CHANGELOG.md
- composer.json
Changelog: https://github.com/openlayers/openlayers/blob/main/changelog/upgrade-notes.md#1000
> Update openlayers backport to version 10.2

- src/Mapbender/ManagerBundle/Resources/public/components.js
- src/Mapbender/ManagerBundle/Resources/public/sass/manager/applications.scss
- src/Mapbender/ManagerBundle/Resources/views/Application/form-elements.html.twig
- src/Mapbender/ManagerBundle/Resources/views/Application/form-layersets.html.twig
Add filter to backend layouts; colour highlighting of search results in backend layouts and backend layersets
see internal ticket 8123
> filter layouts; colour highlighting of search results

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js
Fixes https://github.com/mapbender/mapbender/issues/1642
> Fix max/start extent with negative values

- src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js
- src/Mapbender/CoreBundle/Resources/views/Element/layertree.html.twig
De-/activate layer by clicking layername; 
layername cannot be clicked if the user sets in the backend that the checkbox is not selectable
see ticket 9111
> de-/activate layer by clicking layername

- src/Mapbender/WmsBundle/Element/WmsLoader.php
- src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js
Added parameter "mb-infoformat" to configurations 
see ticket https://easyredmine.wheregroup.com/issues/9416
> Load wms with link: add parameter mb-infoformat

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js
- src/Mapbender/CoreBundle/Resources/public/sass/element/basesourceswitcher.scss
clicking on the top menu closes the group menu
see ticket 9112
> clicking on the top menu closes the group menu

- docs/README.md
- docs/api/setup.md
- src/Mapbender/CoreBundle/Controller/ApiController.php
- src/Mapbender/CoreBundle/EventHandler/ApiFailureHandler.php
- src/Mapbender/CoreBundle/Resources/config/controllers.xml
- src/Mapbender/CoreBundle/Resources/config/services.xml
see https://github.com/mapbender/mapbender-starter/pull/134 for details
> Setup Login for REST API

- CHANGELOG.md
- src/Mapbender/WmtsBundle/Resources/public/geosource-base.js
- src/Mapbender/WmtsBundle/Resources/public/mapbender.geosource.wmts.js
Addition to #1635, WMTS sources were not yet refactored
> Refactor Wmts to use ES6 classes

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.searchRouter.js
> [SearchRouter] Always show "no results" message, independent of results.count setting

- src/Mapbender/ManagerBundle/Resources/views/Element/gpsposition.html.twig
> [GpsPosition] Disable checkbox zoomToAccuracyOnFirstPosition when centerOnFirstPosition is not activated

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js
> [LayerTree] Toggle state of all sublayers when holding shift while toggling a layer

- CHANGELOG.md
- src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js
> Adapt legend url when switching WMS styles

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js
- src/Mapbender/CoreBundle/Resources/public/mapbender-model/VectorLayerBridge.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.model.js
- src/Mapbender/CoreBundle/Resources/public/sass/element/map.scss
fixes #1273 
see internal ticket 4761
> [POI] Add option to minimize and completely remove POI popup

- src/Mapbender/RoutingBundle/Component/RoutingDriver/OsrmDriver.php
- src/Mapbender/RoutingBundle/Element/Type/RoutingAdminType.php
- src/Mapbender/RoutingBundle/Resources/config/services.xml
- src/Mapbender/RoutingBundle/Resources/translations/messages.de.yml
- src/Mapbender/RoutingBundle/Resources/translations/messages.en.yml
Working examples for OSRM urls:
- https://routing.openstreetmap.de/routed-%profile
- https://router.project-osrm.org
> Add `%profile` as template variable in routing url

- src/Mapbender/RoutingBundle/Resources/public/mapbender.element.routing.js
- src/Mapbender/RoutingBundle/Resources/public/sass/mapbender.element.routing.scss
Adds a css class for custom styling purposes to the `ul` autocomplete list.
> [Routing] Add css class for styling purposes

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.simplesearch.js
- src/Mapbender/CoreBundle/Resources/views/Element/simple_search.html.twig
> [SimpleSearch] Fix initially selected configuration was not selected in the dropdown menu

- src/Mapbender/RoutingBundle/Element/Routing.php
- src/Mapbender/RoutingBundle/Element/Type/RoutingAdminType.php
- src/Mapbender/RoutingBundle/Resources/public/mapbender.element.routing.js
see internal issue #9623 
- sets output of routing steps per default to true
- sets zoombuffer per default to 100
- dialog is now resizable
- sets default OSRM route url
- changes default solr configuration
> [Routing] Add miscellanous routing enhancements

- CHANGELOG.md
- src/FOM/UserBundle/Controller/UserController.php
> Fix users could not modify their own profile

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js
- src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js
> [ShareUrl] Fix selected layers not encoded correctly

- src/Mapbender/CoreBundle/Resources/public/sass/element/simple_search.scss
- backgorund for x-Button to show x-button on top of long text
> simple_search.scss add background for x button

- CHANGELOG.md
- src/Mapbender/ManagerBundle/Controller/ElementController.php
- src/Mapbender/ManagerBundle/Resources/public/components.js
- src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.de.yaml
- src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.en.yaml
- src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.es.yaml
- src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.fr.yaml
- src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.it.yaml
- src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.nl.yaml
- src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.pt.yaml
- src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.ru.yaml
- src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.uk.yaml
- src/Mapbender/ManagerBundle/Resources/views/Application/form-elements.html.twig
Elements in Layout-lists can be cloned by clicking on copy-icon;
see ticket 7592
> Cloning of elements enabled

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js
- src/Mapbender/CoreBundle/Resources/public/sass/element/layertree.scss
> [LayerTree] Fix opacity slider did not work together with dimension slider

- CHANGELOG.md
- src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js
Fixes incorrect layer active states in map after loading WMS with WMS-Loader-Links.
-> see Internal #10302
> [WMS-Loader] Fix layer in map not loaded correctly

- src/Mapbender/RoutingBundle/Component/RoutingDriver/OsrmDriver.php
Fixes missing routing information, see internal #10383
> [RoutingBundle] Fix missing start or destination spec in route info

- src/Mapbender/ApiBundle/Controller/CommandController.php
Sorry, this should of course be merged into develop
> [API] Fix controller response if console command throws an error

- CHANGELOG.md
- src/Mapbender/CoreBundle/Element/AboutDialog.php
- src/Mapbender/CoreBundle/Element/ResetView.php
- src/Mapbender/CoreBundle/Resources/public/element/dataupload.js
- src/Mapbender/CoreBundle/Resources/public/element/mapbender.element.coordinatesutility.js
- src/Mapbender/CoreBundle/Resources/public/init/element-sidepane.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.aboutDialog.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.button.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.gpsPosition.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.ruler.js
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.scaleselector.js
- src/Mapbender/CoreBundle/Resources/public/sass/modules/_input.scss
- src/Mapbender/CoreBundle/Resources/public/widgets/mapbender.popup.js
- src/Mapbender/CoreBundle/Resources/views/Element/ShareUrl.html.twig
- src/Mapbender/CoreBundle/Resources/views/Element/basesourceswitcher.html.twig
- src/Mapbender/CoreBundle/Resources/views/Element/dataupload.html.twig
- src/Mapbender/CoreBundle/Resources/views/Element/layertree.html.twig
- src/Mapbender/CoreBundle/Resources/views/Element/sketch.html.twig
- src/Mapbender/CoreBundle/Resources/views/Element/view_manager-listing-row.html.twig
- src/Mapbender/CoreBundle/Resources/views/Element/zoombar.html.twig
- src/Mapbender/CoreBundle/Resources/views/Template/fullscreen.html.twig
- src/Mapbender/CoreBundle/Resources/views/Template/fullscreen/toolbar.html.twig
- src/Mapbender/CoreBundle/Resources/views/Template/region/sidepane.html.twig
- src/Mapbender/FrameworkBundle/Component/Renderer/ElementMarkupRenderer.php
Buttons, control elements and elements in the sidepane can be accessed by clicking the Tab key and triggered with the Enter key; other elements can be operated with the Tab key and arrow keys
> Accessibility: Optimization keyboard operation

- CHANGELOG.md
- src/Mapbender/CoreBundle/Element/Layertree.php
- src/Mapbender/CoreBundle/Element/Type/LayertreeAdminType.php
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js
- src/Mapbender/CoreBundle/Resources/public/sass/element/layertree.scss
- src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.es.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.fr.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.it.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.nl.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.pt.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.ru.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.tr.yaml
- src/Mapbender/CoreBundle/Resources/translations/messages.uk.yaml
- src/Mapbender/CoreBundle/Resources/views/Element/layertree.html.twig
- src/Mapbender/CoreBundle/Resources/views/ElementAdmin/layertree.html.twig
This adds an input field to filter the layertree.
See internal ticket 10202
- activate Layertree filter in Element Layertree via checkbox 
See https://doc.mapbender.org/en/elements/basic/layertree.html
Modify highlight color via css
```
.mb-element-layertree .layer-highlight {
color: #279ddc;
font-weight: bold;
}
```
> Layertree filter function

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/sass/element/featureinfo.scss
Regression after replacing Mapbender.Popup2 by Mapbender.Popup
> [FeatureInfo] Fix iframe did not use full height

- CHANGELOG.md
- src/FOM/UserBundle/Security/Authentication/Provider/SspiAuthenticationProvider.php
- src/Mapbender/CoreBundle/Asset/CssCompiler.php
- src/Mapbender/CoreBundle/Entity/Source.php
- src/Mapbender/ManagerBundle/Component/ElementFormFactory.php
- src/Mapbender/RoutingBundle/Component/RoutingDriver/PgRoutingDBInterface.php
- src/Mapbender/WmsBundle/Command/UrlReloadCommand.php
- src/Mapbender/WmsBundle/Entity/WmsInstanceLayer.php
And also fix "undefined method" warnings elsewhere  in mapbender
> Fix wms:reload and wms:add commands were broken after update

- CHANGELOG.md
- src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js
- src/Mapbender/CoreBundle/Resources/public/sass/element/basesourceswitcher.scss
> [BaseSourceSwitcher] Fix behaviour in sidepane
