mapbender/mapbender

src/Mapbender/PrintBundle/Component/PrintService.php
Fix for application crashes if no fontsize is set. Now it will use default value 20 instead. @swinkelmann Please check before we can merge
=> Fix print default font size setting

src/Mapbender/PrintBundle/Component/PrintService.php
* If you use öüä in group names and want to print the group name to the pdf at the moment öüä are bloken
* just add utf8_decode(..) to display them in the right way
*  utf8_decode($group->getDescription()));
=> add utf8_decode to handle öüä for dynamic textes

src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml
* merged the structure with the en version. same ordering
* fixes some typos f.e. sidepane Buttons instead of Tabs (as Reiter as Reiter is the wŕong translation)
=> fixed typos, merged with en version, changed some translation

src/Mapbender/CoreBundle/Resources/public/sass/element/map.scss
Layer tiles remain non-selectable.
Text inside Openlayers popups becomes selectable again (previously not possible).
Solved by pushing user-select attribute change down from .mb-element-map to a nested .olLayerDiv selector.
This fixes internal ticket #8068.
=> Reenable default text selection in nested elements in map

src/Mapbender/MobileBundle/Resources/public/js/mapbender.mobile.js
fixes #548
edited event listener for searchroutrer result click only on mobile template.
now the search overlay closes if the user clicks an an search-result
=> remove 'move' check on click event

src/Mapbender/CoreBundle/Resources/proj4/proj4js_epsg.txt
See ticket #562 
Checked the EPSG Codes
- 4326 Geographisch, weltweit:
- 25832 ETRS89 / UTM zone 32N und 33N:
- 25833 ETRS89 / UTM zone 32N und 33N:
- 31466 Gauß-Krüger Zonen 2 bis 5:
- 31467 Gauß-Krüger Zonen 2 bis 5:
- 31468 Gauß-Krüger Zonen 2 bis 5:
- 31469 Gauß-Krüger Zonen 2 bis 5:
- 3044 ETRS89 / UTM zone 32N und 33N
- 3045 ETRS89 / UTM zone 32N und 33N
- 5243 ETRS89 / LCC Germany (Lambert) E-N und N-E
- 4839 ETRS89 / LCC Germany (Lambert) E-N und N-E
- 3857 WGS 84 / Pseudo-Mercator -- Spherical Mercator
- 31254 MGI Austria GK West
- 31255 MG Austria GK Central
- 31256 MG Austria GK East
- 3035 ETRS89 / LAEA
- 25832 ETRS89 / UTM zone 32N
- 3068 DHDN / Soldner Berlin
and added the missing ones.
Please delete the branch after merge. Thanks.
=> added EPSG:4839 and EPSG:5243 to the list

src/Mapbender/CoreBundle/Element/FeatureInfo.php, src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js, src/Mapbender/CoreBundle/Resources/translations/messages.de.yml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yml, src/Mapbender/CoreBundle/Resources/translations/messages.es.yml, src/Mapbender/CoreBundle/Resources/translations/messages.pt.yml, src/Mapbender/CoreBundle/Resources/translations/messages.ru.yml, src/Mapbender/CoreBundle/Resources/views/Element/featureinfo.json.twig
…esult
ticket #552 was already fixed with https://github.com/mapbender/mapbender/commit/d11dd2fd1bde139225a388ddb6d125cb24562260
Due to modularisation this solution may be better. Does not need  'MapbenderCoreBundle:Element:printclient.json.twig' in  src/Mapbender/CoreBundle/Element/FeatureInfo.php
=> Hotfix/featureinfo translation for print button mb.core.featureinfo.popup.btn.print

src/Mapbender/CoreBundle/Element/Type/TargetElementType.php
See #586.
This patch replaces usort with array_multisort.
Sorting still functions as expected (observe value ordering in "Type" dropdown of newly created Button element).
It may be worth hunting for similar usort usages in the code and also update them.
=> Replace usort => array_multisort to skip around PHP bug #50688 (MB3 #586)

src/Mapbender/PrintBundle/Component/PrintService.php
* see ticket #555
* Print should not fail when no legend region on first page exists
=> yStartPosition only checked when legend-frame exits

CHANGELOG.md, src/Mapbender/CoreBundle/Component/Signer.php
See internal ticket 8375.
Previously, url signing was not properly handling service URLs with no question mark (before query params). The detected base url length was sometimes 0, allowing client-side URL tampering using the same signature.
Changes in this PR enforce that with any given signature, only requests with the same scheme, host and path will pass signature validation. Client code needs to remain able to modify request type, bbox etc on map services, so enforcing same full url would be too strict.
This branch looks equally mergable on the release/3.0.7 branch.
=> URL signer spoof hardening

src/Mapbender/WmcBundle/Component/WmcParser110.php
Fix to parse WMC documents from Xml files correctly.
There was a default version parameter before, but it doesn't work anymore. :-(
=> WmcParser: small fix to set version parameter in map requests

src/Mapbender/PrintBundle/Component/PrintService.php
* if the template with feature is defined and the template is used in a use case without an feature an error occurs
* the pull request checks this and prevents the error
* in combination with https://github.com/mapbender/mapbender/pull/691
* see ticket #692
=> PrintClient - fixed feature exists

src/Mapbender/WmcBundle/Entity/Wmc.php, src/Mapbender/WmsBundle/Entity/WmsLayerSource.php
Some fields in both entities had the visibility set to protected as a workaround for some prehistoric doctrine bug. But with these visibilities the entities are invalid and doctrine:schema:validate would fail and you could not create a new db with the console commands. The doctrine bug is now fixed, so we can change the visibility to the correct protected value.
=> Change visibility of some fields in WmsLayerSource and Wmc Entites

src/Mapbender/CoreBundle/Element/HTMLElement.php
Fixes issue #707
If the user-editable content of the HTML element is broken enough to cause a Twig error, we log a warning, and fill the element div with a little HTML comment summarizing the error.
The rest of the application remains functional.
=> HTMLElement: handle Twig exceptions, log a warning

src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js
Fixes issue #709
Layer menu moves in the DOM. It's now a sibling instead of a child of the layer-menu-btn.
Embedded checkboxes (e.g. layer dimensions) become functional again.
=> Move layer menu out of button to fix event flow

src/Mapbender/CoreBundle/Component/SourceInstanceEntityHandler.php, src/Mapbender/CoreBundle/Controller/ApplicationController.php, src/Mapbender/CoreBundle/Utils/ArrayUtil.php, src/Mapbender/CoreBundle/Utils/RequestUtil.php, src/Mapbender/WmsBundle/Component/InstanceTunnel.php, src/Mapbender/WmsBundle/Component/InstanceTunnelHandler.php, src/Mapbender/WmsBundle/Component/WmsInstanceEntityHandler.php, src/Mapbender/WmsBundle/Component/WmsInstanceLayerEntityHandler.php, src/Mapbender/WmsBundle/Component/WmsSourceEntityHandler.php
Instance tunnel is used when a service is secured (username + password) to hide auth details from client code.
Instance tunnel legend loopholes were closed in https://github.com/mapbender/mapbender/pull/616
This introduced a regression, losing non-GetLegendGraphic modes of retrieving a legend image for tunneled WMS. Namely, pulling a legend image from a layer's ```<Style>``` block in the capabilities document instead of the top-level ```<GetLegendGraphic>```.
This pull breaks out the logic for legend url selection into freestanding methods.
These methods are then reused as-is in the instance tunnel handling to get the same results for secured and unsecured WMS services.
This fixes the regression introduced in pull 616.
Collateral:
This pull also extends the ```<Style>``` legend picking to …
=> Support non-GetLegendGraphic legends via instance tunnel

src/Mapbender/CoreBundle/Component/Element.php
This replaces [Pull #649](https://github.com/mapbender/mapbender/pull/649). 649 contains a real bug / regression (calculated AdminType class name ends up in wrong namespace, misses `Type` component) and a few unfortunate choices.
This became clear after [anaylzing the existing element base](https://github.com/mapbender/mapbender/blob/enh/element-class-introspection/src/Mapbender/CoreBundle/Command/ElementClassesInspectCommand.php).
Differences to 649:
* auto-calculated AdminType class name is in expected namespace (`SomeBundle\Element\Type\`).
* adds previously missing `getFrontendTemplatePath` method; this was previously hard-baked into the render method
* auto-generation split out of getter logic: [getAutomaticTemplatePath](https://github.com/mapbender/mapbender/blob/eecf8e0df2bdc1b77d04 …
=> [restore BC] fix automatic element template / admin type calcs vs inheritance, noconfig edition

src/Mapbender/WmsBundle/Component/MetadataUrl.php
Fixes #746.
Protected attribute `$url` removed, unused factory method `create` removed. Serialization result becomes valid, storage to database (when adding the WMS as a new source) works, reload works, no more exception on Postgres driver.
Previous database values remain corrupted. View / refresh / delete still not possible with fix. Manual cleanup required.
Recommend identifying the id of the affected source (it's in the backend listing and also in the URLs where you would see the exception), and running
```sql
UPDATE mb_wms_wmslayersource SET metadataurl = NULL WHERE wmssource = <your wms id here>;
```
=> Fix corrupted serialization of MetadataUrl

src/Mapbender/CoreBundle/Tests/SeleniumPhantomJsTest.php, src/Mapbender/CoreBundle/Tests/SeleniumPythonTest.php
Unit tests in mapbender CoreBundle have [naive minor-version checks that will falsely identify PHP7.3 as PHP 5.3 and fail the tests](https://github.com/mapbender/mapbender/blob/9073dd06b57841e32c9369583b5e776f0221c8b1/src/Mapbender/CoreBundle/Tests/SeleniumPhantomJsTest.php#L10).
This pull fixes the version check to require PHP >= 5.4.
This pull also adds a check in the Python/Selenium test that skips the test if no Python or no selenium Python module can be loaded.
This pull also changes the failure mode of preconditions to use a SkippedTestError instead of (previously) IncompleteTestError, following PHPUnit's conventions and internal behaviour on what kind of error to throw when a test can't execute.
=> Fix/unittest preconditions to support PHP7.3

src/Mapbender/WmsBundle/Resources/public/mapbender.element.dimensionshandler.js
There was some "Update the code" commit that introduced a loop over the dimension configuration in layersets, and emptied it, by reference.
This pull fixes that. Dimension configration survives app initialization.
=> Dimension handler: fix lost config in frontend

CHANGELOG.md, src/Mapbender/WmsBundle/Element/WmsLoader.php, src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js, src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js, src/Mapbender/WmsBundle/Resources/translations/messages.de.yml, src/Mapbender/WmsBundle/Resources/translations/messages.en.yml, src/Mapbender/WmsBundle/Resources/translations/messages.es.yml, src/Mapbender/WmsBundle/Resources/translations/messages.fr.yml, src/Mapbender/WmsBundle/Resources/translations/messages.it.yml, src/Mapbender/WmsBundle/Resources/translations/messages.nl.yml, src/Mapbender/WmsBundle/Resources/translations/messages.pt.yml, src/Mapbender/WmsBundle/Resources/translations/messages.ru.yml, src/Mapbender/WmsBundle/Resources/views/Element/wmsloader.html.twig
The Wms Loader element was restructured to use already existing
server side implementations for loading Wms. The checkbox 'only valid'
was also added, because by default, only valid Wms would be loaded.
This fixes https://github.com/mapbender/mapbender/issues/706
=> Fix Wms Loader not using already existing backend implementations

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/sass/modules/_input.scss, src/Mapbender/WmsBundle/Component/WmsInstanceEntityHandler.php, src/Mapbender/WmsBundle/Component/WmsInstanceLayerEntityHandler.php, src/Mapbender/WmsBundle/Entity/WmsInstanceLayer.php, src/Mapbender/WmsBundle/Entity/WmsLayerSource.php, src/Mapbender/WmsBundle/Resources/views/Repository/instance-layer-form.html.twig
Remove default prepopulation of min/max scale on instance layers while creating new WMS instance or reloading existing instance. Effective initial values are still from the source, just like before, but by indirect lookup, not by copy.
Admin can now distinguish between empty, but inherited values and locally replaced values in "Layerset" backend. If no local value set, inherited value is shown as a placeholder with slightly lighter color.
Lookup logic for effective min / max scale, for each layer is now:
* use admin-set value directly on layer instance if present
* if no value set, use value from layer instance's source layer (GetCapabilities)
* if still no value, go up to parent layer instance, which, again, looks at itself first, then its source layer, recursively
This should make …
=> Fix layer min max scale inheritance

src/Mapbender/WmsBundle/Component/WmsInstanceEntityHandler.php, src/Mapbender/WmsBundle/Element/DimensionsHandler.php, src/Mapbender/WmsBundle/Entity/WmsInstance.php
DimensionsHandler used to rewrite the DimensionInst entities attached to the WmsInstance every time you saved its config in the backend. This was only done so its updated configuration could be embedded into the config generated for a loading application.
This behavior has been removed.
The equivalent replacement behavior is to use [the existing app config rewriting mechanism](https://github.com/mapbender/mapbender/commit/00d260ec192300b575d1618f7db6594c66f85675) similarly to [earlier changes in BaseSourceSwitcher](https://github.com/mapbender/mapbender/commit/5bd5681a8d5920079061392fe968b3c30450f5ad#diff-5fe99690b11d0933943310ef0080f0adR198).
Initial motivation / bigger picture:
* resolving abuse of core entities as dumping ground for precached frontend config
* removing paths that …
=> No entity rewrites for DimensionsHandler

src/Mapbender/CoreBundle/Resources/public/mapbender.element.redlining.js
The redlining element now listens on event 'mbmapsourceadded'. If this is triggered, the redlining layer is raised by the number of current layers and the layerZIndex is reset
See ticket: https://github.com/mapbender/mapbender/issues/698
=> Fix #698 load WMS covers redlining

src/Mapbender/ManagerBundle/Resources/public/sass/element/form.scss
This fixes misaligned delete-buttons in admin view for template collections (#799 )
=> Fix misaligned delete button in print admin view

src/Mapbender/CoreBundle/Element/Type/LayerTreeMenuType.php, src/Mapbender/CoreBundle/Element/Type/LayertreeAdminType.php, src/Mapbender/CoreBundle/Resources/config/services.xml, src/Mapbender/WmsBundle/MapbenderWmsBundle.php, src/Mapbender/WmsBundle/Resources/config/services.xml
This is a better, cleaner version of [pull 610](https://github.com/mapbender/mapbender/pull/610/files#diff-005c46c7584cee49cf60354ae9ad5ac0L47), exploring a new "technical preview" delivery for not-quite-ready features that are already in the main code base.
DimensionsHandler has been sleeping in the code base for a while, but it's not ready yet for public consumption. Some projects do use it though, even on older 3.0.5 versions, so we can't just remove it or break it out into its own repository without risking upgrade continuity.
This pull does not enable anything new by default. DimensionsHandler is still kept "hidden". Meaning:
* doesn't show up in the list of addable elements when you edit your application layout
* doesn't show up in LayerTree "menu" choices
This simply changes the …
=> Add config hook to expose DimensionsHandler as a technical preview

src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js
This will prevent the basesource switcher from opening on application startup.
Fixes https://github.com/mapbender/mapbender/issues/785
=> Fix basesourceswitcher automatically opening on startup

src/Mapbender/PrintBundle/Component/PrintService.php
When printing a template with coordinates being printed, the font size was not parsed as an integer, but as a string. This fixes #817
=> Fix coordinate font size NaN

src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js
After https://github.com/mapbender/mapbender/issues/785#issuecomment-384877571 was reopened, this should fix the problem of non-closing BaseSourceSwitcher-menus. 
You actually don't have to click anymore, to open the dropdown menu, hovering over it is enough.
=> Fix BSS menu not closing after selection

src/Mapbender/WmsBundle/Entity/WmsLayerSource.php
Deleting a wms source was causing a foreign key violation in the wms_layersource entitiy. Cascaded deleting fixes this.
This fixes #838
=> Fix foreign key violation

src/Mapbender/WmsBundle/Element/WmsLoader.php, src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js
Teilt die Layer eines WMS-Dienstes in Root-Layer auf.
Diese Funktion war bereits einmal clientseitig implementiert in der jetzt als deprecated markierten `mapbender.geosource.wms.js`: 
https://github.com/mapbender/mapbender/blob/master/src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js#L244
=> WMS Loader: Split WMS

src/Mapbender/Component/SymlinkInstaller/SymlinkInstaller.php
"Null coalesce" `??` is a new PHP7.0 operator.
See http://php.net/manual/en/language.operators.comparison.php
The good old "ternary with no middle part" `?:` is legal since PHP5.3 (as documented on the same manual page).
They are not 100% equivalent. `?:` will take the right value if the left is falsy (empty string etc), while `??` checks strictly and only for null.
I think in this use case the replacement is valid though.
=> Replace PHP7+ '??' operator with PHP5.3-compatible '?:'

src/Mapbender/CoreBundle/Element/PrintClient.php
This PR changes the default prefix for printouts to mapbender instead mapbender3. So a default printout file is now called mapbender_<date> instead of mapbender3_<date>.
=> Change default prefix for printouts to mapbender. Ticket 855

src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.legend.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js, src/Mapbender/CoreBundle/Resources/public/mapbender.geosource.js, src/Mapbender/CoreBundle/Resources/public/mapbender.model.js, src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js, src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js
Status: dynamic reordering of both static and dynamically added sources and layers works as intended. "Themed" layertree was tested as well.
Layer order self-reset on scroll / dynamic layer de-/reactivation has been resolved.
We had some issues with dynamic layer reordering in combination with "Reversed (QGIS style)" layer order in some applications.
The previous code performed a multitude of incremental "Move this layer before this second layer and / or after that third layer" updates to the internal "geosource" data structures, in hopes that the internal structure would always remain in sync with the (visible) DOM order. This was often not the case. Particularly, when many layers were moved in bulk, the before / after layers could point to already moved ones, breaking the process.
The …
=> [WIP] dynamic layer reordering vs reversed layer order

src/Mapbender/CoreBundle/Resources/public/mapbender.element.coordinatesdisplay.js, src/Mapbender/CoreBundle/Resources/public/mapbender.model.ol4.js
Das Fixed den Fehler, dass beim srs switchen ein neuer Mouse Position Control dazugefügt wird:
Jetzt wird ein neuer Mouse Position Control nur in der` setup()` Funktion gesetzt. Beim srs switchen event wird jetzt nur noch die Projektion upgedatet.
=> Fix error add mouse position control

src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js, src/Mapbender/CoreBundle/Resources/public/mapbender.model.ol4.js
Neben `label` und `id` wird doch auch noch `source.configuration.options.tunnel` benötigt für Passwort-geschützte Dienste: 
https://github.com/mapbender/mapbender/blob/ol4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js#L190
Der Ajax-Request sieht dann anders aus
=> Add return source object from collectFeatureInfoObjects()

src/Mapbender/CoreBundle/Resources/views/metadata.html.twig
* see ticket: https://github.com/mapbender/mapbender/issues/836
* links and mail address are displayed as links
=> #836 Layertree metadata dialog show links, mail as links

src/Mapbender/CoreBundle/Entity/Keyword.php
Changed keyword data type back to string. If a source is configured to have a longer keyword list, it will now be cut off after 255 chars.
=> Revert keyword data type back to string Fix #1000

src/Mapbender/CoreBundle/Resources/public/mapbender.geosource.js
Avoid sending FeatureInfo requests with empty layer names. This happens when collecting root or group layers for feature info, and triggers WMS errors.
=> Skip empty layer names when collecting feature info QUERY_LAYERS value

src/Mapbender/CoreBundle/Resources/public/mapbender.element.redlining.js
This fixes #995. After the dialog is closed, only the layer's features are removed, not the layer itself.
=> Fix redlining dialog no second sketch #955

src/Mapbender/CoreBundle/Resources/public/mapbender.element.legend.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js, src/Mapbender/CoreBundle/Resources/public/mapbender.model.js
Fixes #1024 
Ordering of source layers, per-source layer requests, source and sublayer display in Llayertertree, source and sublayer display in Legend no longer depend on any other Element being present or not in the application.
Collateral: order of legends within a source group now matches layertree display order ("high layer" first, "base layer" last).
=> Fix in-place layerSet and child layer order reversals

src/Mapbender/CoreBundle/Resources/public/mapbender.element.copyright.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.printClient.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.redlining.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.ruler.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.scalebar.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.scaledisplay.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.searchRouter.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.sketch.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.srsselector.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.zoombar.js, src/Mapbender/PrintBundle/Resources/public/mapbender.element.imageExport.js, src/Mapbender/WmcBundle/Resources/public/mapbender.element.wmcloader.js, src/Mapbender/WmsBundle/Resources/public/mapbender.element.dimensionshandler.js, src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js
Many many many Element frontend scripts have adopted a [completely dysfunctional `readyCallback` processing machinery](https://github.com/mapbender/mapbender/blob/v3.0.7.4/src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js#L255).
These Elements can only successfully initialize if nobody registers a ready callback through this machinery before they finish initializing. If there is at least one deferred callback, these Elements will attempt to invoke an integer (the list index of the readyCallbacks) as a function and fail to flag themselves ready.
As per Chrome console:
```
> var cbs = [function() { console.log("Hello I am a callback"); }, function() { console.log("I am a second callback"); }];
< undefined
> for (callback in cbs) { callback(); }
< Uncaught TypeError: …
```
=> Remove readyCallback handling from all Elements where it is dysfunctional

src/Mapbender/CoreBundle/Command/VersionCommand.php, src/Mapbender/CoreBundle/DependencyInjection/Compiler/ProvideBrandingPass.php, src/Mapbender/CoreBundle/MapbenderCoreBundle.php, src/Mapbender/CoreBundle/Resources/config/mapbender.yml
Branding, the everlasting joy of life.
This provides Mapbender-internal Mapbender versioning and naming, while still supporting explicit project branding overides.
A new compiler pass displaces [fom: server_version et al](https://github.com/mapbender/mapbender-starter/blob/644dbc24ece67d04bdd9dedcb8baf413d9cc5021/application/app/config/parameters.yml.dist#L20) as the authoritive source of the Mapbender version. Mapbender [gains version knowledge inside itself](https://github.com/mapbender/mapbender/blob/4e86c9f387ac9ee7e3e7737275c9fac29a8d5bce/src/Mapbender/CoreBundle/Resources/config/mapbender.yml#L20).
[Any `server_version` or `server_name` values configured in FOM that follow certain well-treaded patterns are dropped on the floor and replaced by Mapbender's …
=> Internalize mapbender versioning into mapbender repository

src/Mapbender/CoreBundle/Resources/public/mapbender.element.legend.js
property popup is a function so it always will be true-ish. To check if the popup is already open we have to check against property popupWindow. The old code can cause errors if the legend element is used in a button group and breaks the functionality of other buttons in this group.
=> Change check for this.popup to this.popupWindow

src/Mapbender/CoreBundle/Resources/public/mapbender.element.printClient.js, src/Mapbender/PrintBundle/Component/PrintService.php
The printed overview map (pdf) does not 'zoom in' if the overview map element is 'fixed'.
To test this change just configure overview map as fixed and choose a print template with an overview map (a3_landscape_offical_overview)
=> Print fixed Overview Map

src/Mapbender/CoreBundle/Resources/public/mapbender.application.js
Switches Mapbender.ElementRegistry internal machinations to use [promises](https://promisesaplus.com/) as implemented by [jQuery.Deferred](http://api.jquery.com/jQuery.Deferred/).  
Maintains previous public API ([listWidgets](https://github.com/mapbender/mapbender/blob/697d4585f06c4e03376ad273ec096c3b3b1cc1c4/src/Mapbender/CoreBundle/Resources/public/mapbender.application.js#L37), [onElementReady](https://github.com/mapbender/mapbender/blob/697d4585f06c4e03376ad273ec096c3b3b1cc1c4/src/Mapbender/CoreBundle/Resources/public/mapbender.application.js#L29)) while adding new promise-returning methods.   
[waitCreated](https://github.com/mapbender/mapbender/blob/697d4585f06c4e03376ad273ec096c3b3b1cc1c4/src/Mapbender/CoreBundle/Resources/public/mapbender.application.js#L52) returns a promise …
=> Promises based ElementRegistry

src/Mapbender/ManagerBundle/Resources/views/Application/edit.html.twig, src/Mapbender/ManagerBundle/Resources/views/Application/export-form.html.twig, src/Mapbender/ManagerBundle/Resources/views/Application/form-elements.html.twig, src/Mapbender/ManagerBundle/Resources/views/Application/form-layersets.html.twig, src/Mapbender/ManagerBundle/Resources/views/Application/import-form.html.twig, src/Mapbender/ManagerBundle/Resources/views/Application/new.html.twig
Url generates absoulte urls which can cause errors  behind a reverse proxy. Path instead generates relative paths which are safe to use
=> Change twig url function to path

src/Mapbender/CoreBundle/Resources/public/sass/libs/_icons.scss
After the new font-awesome version has been released via "mapbender / vis-ui.js", the path for font-awesome in the icons.scss must be adjusted. After this adjustment the new version 5 will be loaded.
=> Change the font-awesome path for font awesome version 5

src/Mapbender/CoreBundle/Resources/public/mapbender.element.ruler.js
Removes all detection, redetection (on SrsSwitcher interaction) and handling of geodesic vs non-geodesic CRS from Ruler, which makes measurements equal across both CRS families.
The trick here is that [OpenLayers.Control.Measure's geodesic property](https://github.com/openlayers/ol2/blob/master/lib/OpenLayers/Control/Measure.js#L58) works just fine in a non-geodesic CRS.
This change fixes #1026.
=> Fix geodesic measurements in line / area ruler

src/Mapbender/CoreBundle/Resources/views/Element/button.html.twig
In twig "if(variable)" only checks if the value has a non null value but throws an error if the variable is not present, so we need to check this first.
=> Fix broken applications with undefined click configuration

src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js, src/Mapbender/CoreBundle/Resources/public/mapbender.geosource.js, src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js
Fixes non-repeatable behaviour in handling of 'declarative' links that dynamically add or update Wms sources with explicit layers via `mb-wms-layers` attribute _and_ (default) `mb-wms-merge` "1". Previously, the performed operations on the source were different for newly added sources and already loaded sources.  Now a repeated click on the same declarative link performs the same incremental (`mb-layer-merge` omitted or "1") or total (`mb-layer-merge` "0") set of changes to the source.  
Supports `mb-layer-merge` attribute on 'declarative' links as documented. Previously the code respected only the `mb-wms-layer-merge` attribute, which wasn't documented. Now it supports both equivalently.  
Enhanced support for activating layers explicitly even on sources with intermediate group or root …
=> Fix/declarative mb wms layers repeatability + empty group layer names

src/Mapbender/PrintBundle/Component/Geometry/LineLoopIterator.php, src/Mapbender/PrintBundle/Component/Geometry/LineSegment.php, src/Mapbender/PrintBundle/Component/Geometry/LineStringIterator.php, src/Mapbender/PrintBundle/Component/Geometry/Point2D.php, src/Mapbender/PrintBundle/Component/Geometry/Tuple.php, src/Mapbender/PrintBundle/Component/LayerRendererGeoJson.php, src/Mapbender/PrintBundle/Util/CoordUtil.php, src/Mapbender/Utils/InfiniteCyclicArrayIterator.php
Polygonal features generated by Digitizer or similar developments can have quite complex line styling, which has historically not transferred very well into ImageExport / Print.
This pull improves support for high line widths, non-trivial line opacities and line pattern styling. This is achieved by
1) Compositing. The polygon and its outline are both prepared on a temporary sub-canvas, where holes can be cut without undesired removal of base image portions, and where blending artifacts can be avoided by simply turning blending off.
2) Deconstructing the line pattern into individual line and point primitives.
Consider geometries styled like this (browser view, Digitizer):
The best you could previously achieve in a Mapbender printout ended up something like this:
Things of note:
* The …
=> Enh/improved line pattern quality in export + print

src/Mapbender/CoreBundle/Asset/ApplicationAssetService.php, src/Mapbender/CoreBundle/Resources/public/init/element-sidepane.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.base.js
Technical basis for fixing systemic sidepane element visibility issues such as #992.  
Coalesces FOM [`.tabContainerAlt` and `.accordion`](https://github.com/mapbender/fom/blob/release/3.0.6/src/FOM/CoreBundle/Resources/public/js/frontend/tabcontainer.js) event behaviour into a single flow, which long story short ends up calling either a 'reveal' or 'hide' method on an mbBaseElement widget living in a sidepane.
The effect felt by the mbBaseElement is the same for both `Button` and `Accordeon` sidepane types. When a sidepane tab or accordeon slice opens that contains Mapbender Element widgets, `reveal` will be called on them. When it closes, `hide` will be called. Order is `hide` first, `reveal` second.
Sidepanes are required to carry the `sideContent` CSS class for this to work, because …
=> Sidepane interaction hooks for mbBaseElement

src/Mapbender/ManagerBundle/Controller/RepositoryController.php
Resolves issues where a non-root administrator with assigned global Source ACLs is denied from editing a Source.
Updated grant checking logic requires _either_ a global Source grant (=access to all Source objects) _or_ an object-particular grant on the specific Source.  
NOTE: Mapbender does not per default enable assigning case-by-case grants on particular Sources. We only do that for SourceInstance objects in an Application.  
The ACL machinery certainly allows this granularity, and it might well be implemented already in customized projects.
=> Check global and specific Source access grants in combination

src/Mapbender/CoreBundle/Resources/public/init/element-sidepane.js, src/Mapbender/CoreBundle/Resources/public/mapbender.container.info.js
[MapbenderContainerInfo](https://github.com/mapbender/mapbender/blob/v3.0.7.7/src/Mapbender/CoreBundle/Resources/public/mapbender.container.info.js) was devised as a way to help Elements living in sidepanes reacting to the user switching accordion tabs. Unfortunately, _only_ accordion tabs. Plus a bunch of getters for properties of the container.
This change ties a knot between MapbenderContainerInfo and [the recent attempt at more uniform sidepane element control](https://github.com/mapbender/mapbender/blob/0e0506118f4cd7721c7b258c66a9aba3adc5d0fd/src/Mapbender/CoreBundle/Resources/public/init/element-sidepane.js). MCI instances are punched into the element node data if present, and provisions are made to invoke those callbacks, even though MCI itself no longer does any of this itself. …
=> Fix MapbenderContainerInfo-using widget behaviours in button-style sidepanes

src/Mapbender/ManagerBundle/Resources/public/sass/element/form.scss, src/Mapbender/ManagerBundle/Resources/views/Element/map.html.twig
Allows long layerset titles to in the Map Element backend form to take the full width of the container and avoids spillage outside of the container on line breaks.
Before / After image:
The broken CSS declaration for highlighting the hovered item by darkening its background is fixed as well.
Closes #1085.
=> Fix layerset long title overflow, fix broken hover background color change

src/Mapbender/PrintBundle/Component/LayerRendererMarkers.php, src/Mapbender/PrintBundle/Resources/config/services.xml, src/Mapbender/PrintBundle/Resources/public/mapbender.element.imageExport.js
Mapbender has never rendered marker layers in ImageExport or print.  
Now it does. Here's the familiar pin from the POI Element:  
Supports blended marker layers (opacity << 1), icon offsets, arbitrary dpi scaling.  
Does *not* support icon images located outside of <webroot>/bundles/
=> Add marker layer support for ImageExport and Print

src/Mapbender/CoreBundle/Resources/public/mapbender.model.js
Fehler beim Aktivieren von neuen Ebenen wird die richtige Zeit nicht genommen.
Ursaches des Problemes:
der Url wird in 2 properties gespeichert:
- mqLayer.olLayer.url
- source.configuration.options.url
Jedes mal die Zeit im Feature Dimensions von den Benutzer geändert wird, wird NUR source.configuration.options.url mit dem neue Zeit angepasst (wenn der Checkbox im LayerTree nicht selected ist).
mqLayer.olLayer.url behaltet leider den alten Wert (und wird dieser Wert bunutzt um das WMS aufzurufen), wenn der Benutzer die Sichtbarkeit von einen Layer in LayerTree geändert ist.
=> #31 Fehler beim Aktivieren von Ebenen wird die Zeit nicht gesetzt

src/Mapbender/CoreBundle/Entity/SourceInstanceItem.php, src/Mapbender/WmsBundle/Component/WmsInstanceLayerEntityHandler.php, src/Mapbender/WmsBundle/Entity/WmsInstanceLayer.php, src/Mapbender/WmsBundle/Form/EventListener/FieldSubscriber.php
WMS instance layers with an empty title now fall back to the name of the source layer, which (only) changes if / when the source is reloaded.  
This fallback source title is used in the frontend (Layertree, Legend) if the instance layer does not have an explicitly overrridden name.  
This fallback source layer title is also displayed via the related text input's `placeholder` attribute in the instance backend, so if you empty the text field(s) completely, you can see the effective value.  
Because instance layer titles now have an appropriate fallback, instance creation logic is changed to no longer copy the layer source's title onto the instance layer. I.e. they stay empty by default, and the source layer's title applies.
The resulting layer titles on a freshly minted instance are equal …
=> Allow empty wms instance layer titles, use source layer titles as fallbacks

src/Mapbender/WmsBundle/Component/WmsInstanceEntityHandler.php
Just like in a database-based application, this fix allows toggleable root- and sublayers via yaml configuration.
vs.
```yaml
osm:
class: Mapbender\WmsBundle\Entity\WmsInstance
title: OSM Demo
url: https://osm-demo.wheregroup.com/service
version: 1.3.0
layers:
30: { name: osm,    title : Germany OSM Demo WhereGroup,  visible: false, toggle: false, allowtoggle: true }
info_format: text/html
visible: true
format: image/png
transparent: true
tiled: true
opacity: 100
toggle: false
allowtoggle: true
```
=> Fix WmsInstanceEntityHandler not respecting toggle settings

src/Mapbender/CoreBundle/DependencyInjection/Compiler/RewriteFormThemeCompilerPass.php
Pull adds a compiler pass _class_ that can rewrite the default form theme(s). Pass accepts `from`, `to` constructor arguments.  
Pull _does_ _not_ engage this compiler pass in any way.  
This is intended to
* allow Mapbender core to wrestle control over default form theming away from FOM and Mapbender Starter; the main issue here is that rolling out theming fixes across _three_ repositories in a concerted fashion is complex and error prone
* improve project ability to model global theming changes as bundles
Example usage:  
Place into any Bundle class's `build` method (MapbenderCoreBundle works fine):
```php
$container->addCompilerPass(new RewriteFormThemeCompilerPass('FOMCoreBundle:Form:fields.html.twig', 'bootstrap_3_layout.html.twig'));
```
This makes every form in the entire Mapbender …
=> Add new (dormant) compiler pass that can modify default form themes

src/Mapbender/CoreBundle/Utils/UrlUtil.php, src/Mapbender/WmsBundle/Controller/RepositoryController.php
Closes #1148 
Value is appended when building the reload form, which allows inspection and editing by the operator naturally. If the previously used originUrl already had a version in it, nothing changes at all.
Change only applies to WMS.
=> Amend previously detected WMS version onto originUrl when reloading source

src/Mapbender/CoreBundle/Command/ApplicationCloneCommand.php, src/Mapbender/CoreBundle/Command/ApplicationImportCommand.php, src/Mapbender/CoreBundle/Resources/config/services.xml, src/Mapbender/ManagerBundle/Component/ImportHandler.php, src/Mapbender/ManagerBundle/Controller/ApplicationController.php
With the current release copied application do not have an ACL at all. If you open the Security Tab only the default table will be loaded and it only seems that there are ACEs set. This result in a behavior that global ACEs will not have any impact on these applications access and you could copy and existing application and does not have access to the newly created one.
=> Fix missing permissions after coping an application

src/Mapbender/CoreBundle/Asset/TranslationCompiler.php, src/Mapbender/CoreBundle/Resources/config/services.xml
Requirements for JavaScript-available translations previously only support `.json.twig` inputs, which require maintenance and can be error prone (translation key mapping mismatches).
This pull adds optional support for Element::getAssets and Template::getAssets to include in their return value list for `trans` assets:
1) direct translation keys, e.g. `mb.core.featureinfo.error.nolayer`
2) translation key prefixes ending in a `*` wildcard, e.g. `mb.core.featureinfo.*` or even `mb.core.f*`
Wildcard prefixes expand to a list of every available translation where the key starts with that prefix. This allows extending available messages for Elements simply by adding more messages with the appropriate prefix to a catalog file (messages.en.yml et al in any activated bundle).
Note: direct key …
=> Support direct key (+wildcards) translation requirements

src/Mapbender/PrintBundle/Component/PrintService.php
The newly generated pixel from rotating the image(corners) will be white instead of transparent if alpha is zero. So north arrow overlapping the map has white corners.
=> Change alpha value to 127 instead of 0

src/Mapbender/CoreBundle/Element/Map.php, src/Mapbender/CoreBundle/Element/Type/MapAdminType.php, src/Mapbender/CoreBundle/Resources/public/mapbender.model.ol4.js, src/Mapbender/CoreBundle/Resources/translations/messages.de.yml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yml
Makes stepless zoom behaviour configurable. This is useful to increase visual quality of services that are cached on very particular resolution steps only.
We introduce a new configuration option `fixedZoomSteps` on the Map Element. This is a boolean and defaults to false (=previous behaviour, allowing any intermediate map resolution). When true, scale denominator snaps to one of the values given in the `scales` option (also in Map Element).
=> Add Map configuration option to disable fractional zoom

src/Mapbender/CoreBundle/Resources/public/init/frontend.js
'json' is not a valid content type. 
This causes problems whenever a firewall with a strict set of rules is involved.
=> Fix config request content type

src/Mapbender/CoreBundle/Resources/views/frontend.html.twig
- css can not be found on windows in frontend
- was fixed in manager.html.twig 
- see ticket https://github.com/mapbender/mapbender/issues/1369
=> Fix missing colorpicker assets on windows in frontend

src/Mapbender/FrameworkBundle/EventListener/AutomaticLocaleListener.php, src/Mapbender/FrameworkBundle/Resources/config/services.xml
Auto-detects browser language preference to control translation target language. This takes precedence over the configured default locale.
Adds a new parameter `mapbender.automatic_locale` (boolean; default true) to disable auto-detection. This is intended mainly to aid in testing different language translations.
=> Prefer browser locale

src/Mapbender/CoreBundle/Resources/views/Element/link_button.html.twig
- https://github.com/mapbender/mapbender/issues/1383
- only show label, when checkbox show label is activ
=> link element label visibility - fix for ticket 1383

src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js
This fix resolves issues with downloading linked ZIP files.
If PDF files are not displayed inline in Chrome, the download now also works with this fix.
=> Fixed Download PDF/ZIP Files GetFeatureInfo #1377

src/Mapbender/CoreBundle/Element/Type/IconClassType.php
copyright is an Mapbender element and does not have a button yet.
The css for 'iconCopyright' is already defined in the file _icons.scss. 
With this PR it can be used for as button icon for the element copyright.
https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/public/sass/libs/_icons.scss#L75
=> add iconCopyright to the icon array

src/Mapbender/CoreBundle/Element/Sketch.php, src/Mapbender/CoreBundle/Resources/public/element/sketch.js, src/Mapbender/CoreBundle/Resources/public/element/sketch.scss, src/Mapbender/CoreBundle/Resources/translations/messages.de.yml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yml, src/Mapbender/CoreBundle/Resources/views/Element/sketch.html.twig
Adds manual circle radius editing to Sketch element.
Initial circle drawing remains freehand. Radius can only be edited after circle drawing is completed.
Comes bundled with a slight Sketch usability overhaul in sidepane mode, hopefully resolving some confusion about the semantics of the label input.
A feature that is currently being edited is now marked with a little icon for clarity.
Label (and potentially the new radius) input field(s) now pop out from the table row, making it much clearer what feature they will affect.
Due to unresolved layouting issues, popovers are _not_ used when Sketch is operated as a dialog (i.e. placed in "content" region and opened with a button or automatically). In this case, there is only on (set of) input field(s), shared between editing and new features. …
=> Sketch: editable circle radius

src/Mapbender/CoreBundle/Element/FeatureInfo.php, src/Mapbender/CoreBundle/Element/Type/FeatureInfoAdminType.php, src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js, src/Mapbender/CoreBundle/Resources/translations/messages.de.yml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yml, src/Mapbender/CoreBundle/Resources/views/ElementAdmin/featureinfo.html.twig
For [renderable features extracted from FeatureInfo HTML responses](https://github.com/mapbender/mapbender/pull/1270), stroke color and opacities have [previously](https://github.com/mapbender/mapbender/pull/1323) been hardcoded.
Pull extends configurability and allows customizing stroke color and feature opacity, separately for default rendering and hover states.
For Yaml applications, use the new configuration values `strokeColorDefault`, `strokeColorHover`, `opacityDefault` and `opacityHover`. _NOTE_ that previous `featureColorDefault` and `featuerColorHover` have been renamed to `fillColorDefault` and `fillColorHover` to reduce amgibuity.
Colors should be in CSS six-digit hex format (including leading `#`). Opacities are percentages.
```yml
featureinfo:
class: …
```
=> FeatureInfo: Extend feature coloring options

src/Mapbender/CoreBundle/Element/Sketch.php, src/Mapbender/CoreBundle/Element/Type/SketchAdminType.php, src/Mapbender/CoreBundle/Resources/public/element/sketch.js, src/Mapbender/CoreBundle/Resources/public/element/sketch.scss, src/Mapbender/CoreBundle/Resources/public/mapbender-model/VectorLayerBridgeOl4.js, src/Mapbender/CoreBundle/Resources/translations/messages.de.yml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yml, src/Mapbender/CoreBundle/Resources/views/Element/sketch.html.twig
Adds a multi-entry color pallette to Sketch element to replace the previous hardcoded red default.
Main pallette entries are predetermined by element configuration. The default (as seen above) is to offer red, green and blue.
Additionally, users can edit their own extra color with a color picker.
Clicking on one of the color buttons determines the color for the next feature drawn, or, if currently editing a feature (click on edit icon in table listing), immediately updates that feature to that color.
If the element is configured with only a single color _and_ the frontend color picker is disabled, the pallette region is not shown.
For yaml elements:
```yaml
class: Mapbender\CoreBundle\Element\Sketch
colors:          # new; optional list of strings; use CSS hex notation; omit completely …
```
=> Sketch: multiple, configurable drawing colors + frontend customizable color

src/Mapbender/CoreBundle/Asset/ApplicationAssetService.php, src/Mapbender/CoreBundle/MapbenderCoreBundle.php, src/Mapbender/CoreBundle/Resources/config/services.xml, src/Mapbender/CoreBundle/Resources/config/templates.xml, src/Mapbender/FrameworkBundle/Component/ApplicationTemplateRegistry.php, src/Mapbender/FrameworkBundle/Component/Renderer/ApplicationMarkupRenderer.php, src/Mapbender/FrameworkBundle/DependencyInjection/Compiler/RegisterApplicationTemplatesPass.php, src/Mapbender/FrameworkBundle/MapbenderFrameworkBundle.php, src/Mapbender/FrameworkBundle/Resources/config/services.xml, src/Mapbender/IntrospectionBundle/Command/InspectTranslationTwigsCommand.php, src/Mapbender/IntrospectionBundle/Resources/config/commands.xml, src/Mapbender/ManagerBundle/Controller/ApplicationController.php, src/Mapbender/ManagerBundle/Extension/Twig/ApplicationRegionTitleExtension.php, src/Mapbender/ManagerBundle/Form/Type/Application/RegionPropertiesMapper.php, src/Mapbender/ManagerBundle/Form/Type/Application/RegionPropertiesType.php, src/Mapbender/ManagerBundle/Form/Type/Application/TemplateChoiceType.php, src/Mapbender/ManagerBundle/Resources/config/controllers.xml, src/Mapbender/ManagerBundle/Resources/config/services.xml, src/Mapbender/MobileBundle/MapbenderMobileBundle.php, src/Mapbender/MobileBundle/Resources/config/templates.xml
Application template classes in Mapbender are PHP classes determining the region structure, region-specific form types, twig skins for frontend rendering and so forth.
Changes in this pull replace and extend the (circa 2013) template registration mechanism.
Template classes can now be declared as services tagged with `mapbender.application_template`.
The tag can optionally carry a `replaces` attribute. This allows replacing a shipping mapbender template completely with a project-specific class. A `priority` attribute can also be set to resolve bundle loading order conflicts.
```xml
<service id="project.application_template.custom_fullscreen"
class="ProjectBundle\CustomFullscreen">
<tag name="mapbender.application_template" replaces="Mapbender\CoreBundle\Template\Fullscreen" />
</services> …
```
=> Application template class dropins

src/Mapbender/FrameworkBundle/EventListener/AutomaticLocaleListener.php
A [Dutch translation](https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Resources/translations/messages.nl.yml) has been part of Mapbender for a long time. With this fix it can be used again.
=> Activation of the supplied Dutch translation

src/Mapbender/CoreBundle/Controller/UserInfoController.php, src/Mapbender/CoreBundle/Resources/config/controllers.xml, src/Mapbender/CoreBundle/Resources/public/mapbender.application.js, src/Mapbender/FrameworkBundle/Component/UserInfoProvider.php, src/Mapbender/FrameworkBundle/Resources/config/services.xml
Adds a global userinfo.json url to help with user specific client-side logic.
Adds a client-side `Mapbender.loadUserInfo` method (returns a Promise-like) that will reuse the response if already fetched.
Default implementation returns a `name` (string or null for anons only), `roles` (list of strings) and a convenient `isAnonymous` boolean.
```js
Mapbender.loadUserInfo().then(function(info) {
console.log("User info received", info);
});
```
For a fully authenticated user, the promise resolves with something like this:
```json
{
"name": "root",
"roles": [
"ROLE_GROUP_TESTING-GROUP",
"ROLE_USER"
],
"isAnonymous": false
}
```
For anons, expect this:
```
{
"name": null,
"roles": [],
"isAnonymous": true
}
```
=> Client side user info

src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml
- mb.manager.visibility and not mb.manager.toolbar.visibility
- fixes as defined in german version
=> fixed the mb.manager.visibility definition

CHANGELOG.md, src/Mapbender/CoreBundle/Component/IconPackageFa4.php, src/Mapbender/CoreBundle/Element/Type/IconClassType.php, src/Mapbender/CoreBundle/Resources/public/widgets/dropdown.js, src/Mapbender/CoreBundle/Resources/views/form/fields.html.twig
- In the Button element, show icon previews in the icon selection dropdown
- Add twig template option `dropdown_elements_html` which, when set, won't encode dropdown elements
- Add font awesome icons `home` and `sign-out`
fixes #1258
=> [Button] Show icon previews

CHANGELOG.md, src/Mapbender/CoreBundle/Element/ScaleDisplay.php, src/Mapbender/CoreBundle/Element/Type/ScaleDisplayAdminType.php, src/Mapbender/CoreBundle/Extension/Twig/NumberExtension.php, src/Mapbender/CoreBundle/Resources/config/services.xml, src/Mapbender/CoreBundle/Resources/public/mapbender.element.scaledisplay.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.scaleselector.js, src/Mapbender/CoreBundle/Resources/public/widgets/dropdown.js, src/Mapbender/CoreBundle/Resources/translations/messages.de.yml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yml, src/Mapbender/CoreBundle/Resources/views/Element/scaledisplay.html.twig, src/Mapbender/CoreBundle/Resources/views/Element/scaleselector.html.twig, src/Mapbender/ManagerBundle/Resources/public/sass/element/form.scss
- Add thousand separators in all places within the two elements (using JS's [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) and PHP's [NumberFormatter](https://www.php.net/manual/de/numberformatter.create.php))
- Fix bug where the current scale in the scale select element became blank after selecting a scale
- Make the scale prefix localisable in scale display
- Set default prefix in scale display to a localised string
- Localised backend form of scale display and added help texts
=> Improve scale select and scale display elements

CHANGELOG.md, src/FOM/UserBundle/Command/FixAceOrderCommand.php, src/FOM/UserBundle/Controller/GroupController.php, src/FOM/UserBundle/Controller/UserController.php, src/FOM/UserBundle/Form/Type/UserPasswordMixinType.php, src/FOM/UserBundle/Form/Type/UserType.php, src/FOM/UserBundle/Resources/config/commands.xml, src/FOM/UserBundle/Resources/config/controllers.xml, src/FOM/UserBundle/Resources/views/Group/list.html.twig, src/FOM/UserBundle/Resources/views/User/list.html.twig, src/FOM/UserBundle/Service/FixAceOrderService.php
The (deprecated) symfony/acl-bundle has a bug that prevents an access control list (ACL) from being saved,
when a security identify (e.g. a user) was deleted that had an entry in the component's ACL and was not the
last one in the list. The ACL expects the ace_order column to start with zero and increase one by one,
otherwise array indexing fails.
For example: An application has access rights for user A, B and C. User B is deleted. Then, the acl_entries
table will have only entries for users A (ace_order 0) and C (ace_order 2) which can't be saved anymore.
Implemented workaround: After deleting groups or users (and after manual trigger), a service goes through the whole acl_entries table and resets the indices of entries where the ace_order contains gaps.
=> Security settings could not be saved if a user or group where access control has been previously defined is deleted

CHANGELOG.md, src/Mapbender/CoreBundle/Controller/ComponentsController.php, src/Mapbender/CoreBundle/Resources/public/jquery-ui-touch-punch/jquery.ui.touch-punch.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js, src/Mapbender/CoreBundle/Resources/views/index.html.twig, src/Mapbender/MobileBundle/Resources/public/sass/theme/mobile.scss
- Add jquery-ui-touch-punch library for touch support
- Do not close mobile pane when selecting a theme (see #1404)
- Do not disable sortable functionality in layertree when on devices that support touch
- Fix z-index of mobile pane so it is always above map elements like the simple search
=> Fixes in LayerTree element concering sorting

composer.json
Trivial composer.json dependency version unlock.
Allows updating mapbender/openlayers6-es5 to 7.* versions (presently at [7.3.0.0](https://github.com/mapbender/openlayers6-es5/releases/tag/7.3.0.0)).
Openlayers 7.3.0 contains many performance fixes and other enhancements (e.g. WebGL vector tile rendering etc).
=> Allow installation of Openlayers 7 container package

src/Mapbender/WmsBundle/Component/Style.php
Mapbender 3.2.5 removed properties from WmsBundle/Component/Style ([see commit](https://github.com/mapbender/mapbender/commit/f318cc6611ecfdfa6a036e6ba76d77d512ba3b2e)). The style is stored serialised in the database. PHP 8.2 does not ignore unknown properties like previous version but issues a deprecated message that symfony converts into an error (see [PHP changelog](https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties)).
As a workaround, overwrite `__unserialize` and check for known properties ignoring the old ones.
=> Fix style cannot be unserialized when updating from mapbender <3.2.5 versions in PHP >= 8.2

CHANGELOG.md, composer.json, src/Mapbender/CoreBundle/Asset/ApplicationAssetService.php, src/Mapbender/CoreBundle/Asset/AssetFactoryBase.php, src/Mapbender/CoreBundle/Asset/Base64VLQ.php, src/Mapbender/CoreBundle/Asset/JsCompiler.php, src/Mapbender/CoreBundle/Asset/SourceMapBundler.php, src/Mapbender/CoreBundle/Controller/AssetsController.php
To greatly improve debugging experience in mapbender, the generated js and css files in dev mode will now provide a source map. The debug markers are removed in the process, finding them in a 5 MB, >100.000 lines file was not convenient anyway.
Limitations:
- does only work in local installations since the source files are not publicly exposed
- works in chrome, not flawlessly in firefox though. The file protocol is weakly supported there
=> Add sourcemap support

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/mapbender.element.button.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js, src/Mapbender/CoreBundle/Resources/public/util.js, src/Mapbender/MobileBundle/Resources/public/js/mapbender.mobile.js
- Feature Info now working again in mobile template. The problem here was, that `util:checkReponsiveVisibility` checked only for visibility, but not why the element was invisible. Added check for ''hide-screentype-*" classes.
- When feature info is managed via a button, it is now prevented that the mobile popup appears each time the state is toggled
fixes #1467
=> Fixes for FeatureInfo in Mobile Template

CHANGELOG.md, src/Mapbender/CoreBundle/Element/Map.php, src/Mapbender/CoreBundle/Element/Type/MapAdminType.php, src/Mapbender/CoreBundle/Resources/config/services.xml, src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js, src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml, src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml, src/Mapbender/ManagerBundle/Resources/views/Element/map.html.twig
Mapbender did not show scale-dependent WMS layers on the map when the minimum scale is set. The layer tree shows the corresponding layer as active, but nothing was shown on map. Limit values from map files are used (no overwriting via layer settings in the MB backend).
Solution: The base resolution from Mapbender (96dpi)  did not match with the WMS layer's resolution. The base resolution is now configurable in the map element.
=> Add base dpi setting to map element to circumvent discrepancies in Mapbender and WMS resolutions

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js
If a WMS instance is configured like this
and this source is part of a BaseSourceSwitcher, it is expected to be toggled when switching between base sources. This did not work before this fix because the method responsible for activating layers did also check the "allow selected" checkbox. This checkbox should only be relevant to the layer tree but not for the base source switcher.
=> [BaseSourceSwitcher] Element behaved incorrectly when "allow selected" was not set in the WMS instance

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js, src/Mapbender/CoreBundle/Resources/public/mapbender-model/source.js, src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js, src/Mapbender/WmtsBundle/Resources/public/geosource-base.js
After a source update, the locally stored id's of wms layers won't be updated as well and therefore miss to restore the layertree. This branch provides a solution, matching the layer by name in case of missing id.
=> [LayerTree] Restore layertree configuration after source update

src/Mapbender/CoreBundle/Resources/views/Login/box.html.twig
- login page no : as fom.server_name can be empty, then the tab will contain ": Login" as text
- Please merge to version 4
=> login page no : as fom.server_name can be empty

src/Mapbender/CoreBundle/Component/SQLSearchEngine.php
Replace deprecated QueryBuilder::execute() by executeQuery()
Error introduced after updating of doctrine DBAL
=> Fix search

CHANGELOG.md, src/Mapbender/CoreBundle/Element/SearchRouter.php, src/Mapbender/CoreBundle/Resources/public/element/csv-export.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.searchRouter.js, src/Mapbender/CoreBundle/Resources/translations/messages.de.yml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yml, src/Mapbender/CoreBundle/Resources/translations/messages.es.yml, src/Mapbender/CoreBundle/Resources/translations/messages.fr.yml, src/Mapbender/CoreBundle/Resources/translations/messages.it.yml, src/Mapbender/CoreBundle/Resources/translations/messages.nl.yml, src/Mapbender/CoreBundle/Resources/translations/messages.pt.yml, src/Mapbender/CoreBundle/Resources/translations/messages.ru.yml, src/Mapbender/CoreBundle/Resources/translations/messages.tr.yml, src/Mapbender/CoreBundle/Resources/translations/messages.uk.yml
-> merge request to develop
- add new option to export the result list to csv (without geometry)
- csv ist for download as download.csv
- option exportcsv: true has to be added (defult for exportcsv is false)
- count: true definition was not validated. This is handled in the PR too
- csv content
-  first row is header as defined for the table
- then the values all in quotes "
- if a values is empty ,NULL, exported in the csv -> is that ok? oder better ,,?
```
results:
view: table
count: false
exportcsv: false
```
Example for the content of a download.csv
```
"Name","Gemeinde","Bundesland","Einwohner","Höhe"
"Bonn","Bonn","Nordrhein-Westfalen","109397","59"
"Bonndorf","Überlingen","Baden-Württemberg",NULL,"544"
```
This is how it looks in the application (in Version 4 the translation done)
=> Feature/searchrouter exportcsv - add new option to export result list as csv

CHANGELOG.md, UPGRADING.md, composer.json, src/Mapbender/CoreBundle/Asset/ApplicationAssetService.php, src/Mapbender/CoreBundle/Component/Application/Template/IApplicationTemplateAssetDependencyInterface.php, src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js, src/Mapbender/CoreBundle/Resources/public/mapbender.application.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.legend.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.searchRouter.js, src/Mapbender/CoreBundle/Resources/public/mapbender.geosource.js, src/Mapbender/CoreBundle/Resources/public/util.js, src/Mapbender/CoreBundle/Resources/public/widgets/mapbender.popup.js, src/Mapbender/PrintBundle/Resources/public/element/printclient.js, src/Mapbender/WmsBundle/Resources/public/backend/dimensionshandler.js, src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js
The library was only used sparsely and was not worth the effort of keeping up to date. The following replacements can be used:
- `_.assign`, `_.extend`: `Object.extend`
- `_.debounce`: `Mapbender.Util.debounce`
- `_.difference`: Write manully (one-liner)
- `_.each`, `_.forEach`: `Array.prototype.forEach` or `JQuery.each`
- `_.findWhere`: `Mapbender.Util.findFirst`
- `_.mapObject`: Write manully (three-liner)
- `_.object`: Write manully (three-liner)
- `_.omit`, `_.filter`: `Mapbender.Util.filter`
- `_.uniq`: `Mapbender.Util.array_unique`
=> Remove underscore dependency

CHANGELOG.md, src/Mapbender/CoreBundle/Component/IconPackageFa4.php, src/Mapbender/CoreBundle/Component/IconPackageMbIcons.php, src/Mapbender/CoreBundle/Resources/config/mapbender.yaml, src/Mapbender/CoreBundle/Resources/config/services.xml
Added three parameters (that can be added to your parameters.yaml file):
**`mapbender.icons.disable_default`** (default: `false`):  
if set to true, the default icons from the mapbender namespace are disabled in the button edit form. These are Layer tree, Feature Info, Area ruler, Polygon, Line ruler, Image Export, Legend and About
**`mapbender.icons.disable_default_fa`** (default: `false`):  
if set to true, the default font awesome icons are disabled in the button edit form. These are all others currently available that are not in the mapbender namespace.
**`mapbender.icons.custom`** (default: `~`):  
allows adding more icons from FontAwesome (list available here: https://fontawesome.com/search?o=r&m=free)  
The parameter is an array ob objects containing three keys:
- `name`: …
=> Draft. Allow customization of the icons available for selection in the button edit form

CHANGELOG.md, src/FOM/UserBundle/Resources/config/services.xml
- Fixes the path to the user class of the currently used MapbenderLDAPBundle.
- Allows to secure an application with an LDAP-User again.
=> Fix path to LDAP-userclass

CHANGELOG.md, src/FOM/CoreBundle/Resources/translations/messages.de.yaml, src/FOM/CoreBundle/Resources/translations/messages.en.yaml, src/FOM/ManagerBundle/Resources/translations/messages.de.yaml, src/FOM/ManagerBundle/Resources/translations/messages.en.yaml, src/FOM/UserBundle/Resources/translations/messages.de.yaml, src/FOM/UserBundle/Resources/translations/messages.en.yaml, src/Mapbender/CoreBundle/Command/TranslationCommand.php, src/Mapbender/CoreBundle/Resources/config/commands.xml, src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml, src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.de.yaml, src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.en.yaml, src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.uk.yaml, src/Mapbender/PrintBundle/Resources/translations/messages.de.yaml, src/Mapbender/PrintBundle/Resources/translations/messages.en.yaml, src/Mapbender/WmsBundle/Form/Type/WmsInstanceInstanceLayersType.php, src/Mapbender/WmsBundle/Resources/translations/messages.de.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.en.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.it.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.uk.yaml, src/Mapbender/WmtsBundle/Resources/translations/messages.de.yaml, src/Mapbender/WmtsBundle/Resources/translations/messages.en.yaml
The console command `mapbender:normalize-translations` does three things:
- sort all translation keys in all bundles in the `Mapbender` and `FOM` namespace in the same order as in the original translation file (usually English)
- show keys that are present in the translated file but not in the original translation file
- show (option `-p`) or automatically add (`-a`) keys that are not yet translated. Automatically added keys use the original translation marked with a configurable prefix (`--missing-key-prefix`, default: "TRANSLATE")
Show (print to console) all missing German translations:
```bash
bin/console mapbender:normalize-translations -p de
```
Automatically add all missing Spanish translations to the yaml files:
```bash
bin/console mapbender:normalize-translations -a es
```
```bash …
```
=> New console command `mapbender:normalize-translations`

CHANGELOG.md, src/Mapbender/CoreBundle/Element/Type/MapbenderTypeTrait.php, src/Mapbender/CoreBundle/Form/Type/Template/Fullscreen/SidepaneSettingsType.php, src/Mapbender/CoreBundle/Resources/config/services.xml, src/Mapbender/CoreBundle/Resources/public/jquery-ui-touch-punch/jquery.ui.touch-punch.js, src/Mapbender/CoreBundle/Resources/public/sass/theme/mapbender3.scss, src/Mapbender/CoreBundle/Resources/public/widgets/sidepane.js, src/Mapbender/CoreBundle/Resources/views/Template/region/sidepane.html.twig, src/Mapbender/CoreBundle/Resources/views/index.html.twig, src/Mapbender/CoreBundle/Template/Fullscreen.php, src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.de.yaml, src/Mapbender/ManagerBundle/Resources/translations/messages+intl-icu.en.yaml
Adds an option to the side pane region's properties in the default Fullscreen template:
It is active by default. The key for yaml applications is `resizable`.
Users can now drag the side pane on its right edge to make it smaller or larger. 
By default, the minimum size is 120px. the maximum is 95% of the screen's width. These values can be further restricted by using custom css:
```css
.sidePane.resizable {
min-width: 200px;
max-width: 500px;
}
```
=> Make side pane user-resizable

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js
If a user activates a layer in the layertree by clicking the checkbox, what he/she wants is to see the layer on the map. Until now, this was only the case when all parent layers were already active. With this change, all parent layers will automatically become active when one of its children becomes active.
Also, refactored the initMenu and filterMenu functions to greatly simplify extending the menu with custom functionality.
=> [LayerTree] Ensure all parent layers become visible when toggling a child layer

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/widgets/mapbender.popup.js
Until now it was possible to drag a popup window (like print or legend) outside  the viewport by releasing the mouse button outside the current browser window. The dialog was then gone until the respective element was disabled and reenabled.
New restrictions:
- a popup window's left edge may never be placed further left than the left of the viewport
- a popup window's top edge may never be placed further left than the top of the viewport
- a popup window's right edge may never be placed further than 50px from the right edge of the viewport (which leaves the heading visible so it can be dragged back to the main screen)
- a popup window's bottom edge may never be placed further than 50px from the bottom edge of the viewport (which leaves the heading visible so it can be dragged back to the …
=> Prevent dragging a popup window outside the viewport

CHANGELOG.md, src/Mapbender/CoreBundle/Element/Layertree.php, src/Mapbender/CoreBundle/Element/Type/LayertreeAdminType.php, src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js, src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.es.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.fr.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.it.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.nl.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.pt.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.ru.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.tr.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.uk.yaml, src/Mapbender/CoreBundle/Resources/views/ElementAdmin/layertree.html.twig
The meaning of the option was highly ambigious and its use is very limited for its prominence in the layertree editor.
Use the following custom css to hide all disabled checkboxes:
```css
.leaveContainer > .-fn-toggle-selected.disabled
{
display: none;
}
```
and this code to only hide disabled checkboxes on the top level (matches the behaviour of the old `hideSelect` setting:
```css
.mb-element-layertree > .layers > .leave > .leaveContainer > .-fn-toggle-selected.disabled
{
display: none;
}
```
fixes #1445
=> Remove option "hideSelect" from layertree

CHANGELOG.md, src/Mapbender/PrintBundle/Component/Transport/ImageTransport.php, src/Mapbender/PrintBundle/Resources/config/services.xml
Currently if downloadImage() is unable to download an image, it tries to do the Gd-Operations on null.
Instead downloadImage() should check if $image is null. With this patch, if $image is indeed null an error gets logged (since a null image is undesirable, but a failed download is not necessarily the wrong behaviour for a system) and returns null. This requires a new argument to downloadImage() ($logger), which all callers have to pass. Most already have a $logger that can be used, but LegendHandler.php does not, so a new normally-null logger is introduced and set from PrintService.
Fixes #1549 
Original PR: #1550 by @enno-t
=> [ImageTransport] Return null if image download fails

CHANGELOG.md, src/Mapbender/CoreBundle/Asset/TranslationCompiler.php, src/Mapbender/CoreBundle/Resources/config/services.xml
Previous (buggy behaviour): If a wildcard translation was defined in an element's required assets and none of the wildcard strings was defined in the target language, the TranslationCompiler threw an error causing no translations at all to be available. 
New behaviour: For wildcard translations the fallback locale's translation is used like it already was the case for non-wildcard translations.
=> Fix wildcard translation fallback language if not defined in the target language

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js
This enhances the `visiblelayers` url parameter to work with given source- and layer-name also. So far only source- and layer-ID are allowed.
@astroidex Please test if it works as expected.
see documentation to find out about visiblelayers
https://doc.mapbender.org/en/elements/basic/map.html#make-layer-visible
?visiblelayers=Mapbender/Mapbender_Names,Mapbender/Mapbender_User,39/149
=> Fix visiblelayers param to work by name

CHANGELOG.md, src/Mapbender/CoreBundle/Controller/AssetsController.php, src/Mapbender/CoreBundle/Resources/config/controllers.xml, src/Mapbender/CoreBundle/Resources/config/services.xml
Added new parameters:
-  `mapbender.manager.manager.template_class` (default value: Mapbender\ManagerBundle\Template\ManagerTemplate)
-  `mapbender.manager.manager.login_template_class` (default value: Mapbender\ManagerBundle\Template\LoginTemplate)
If you want to customize the css of your application's backoffice, overwrite the parameters with the FCQN of a class that implements `Mapbender\Component\Application\TemplateAssetDependencyInterface` (or extends from the mapbender core's ManagerTemplate)
=> Make manager template and login template configurable in AssetsController

CHANGELOG.md, src/Mapbender/PrintBundle/Component/OdgParser.php, src/Mapbender/PrintBundle/Component/PrintService.php, src/Mapbender/PrintBundle/Component/TemplateRegion.php
Previously, all generated text from print templates was left-aligned. Now, the alignment of text fields used in LibreOffice Draw is repected.
=> [PrintClient] Parse text alignment when parsing ODG for print templates

src/Mapbender/ManagerBundle/Resources/public/sass/manager/manager.scss, src/Mapbender/ManagerBundle/Resources/public/sass/manager/services.scss
Increases the contrast of checkboxes in the backend for better visibility.
Please check if the style is OK like that.
=> Increase contrast of checkboxes in backend

CHANGELOG.md, src/FOM/UserBundle/EventListener/FailedLoginListener.php, src/Mapbender/CoreBundle/Entity/Element.php
When logging in and the login could not be assigned to a user an exception occured.
=> Do not crash when passport does not exist in FailedLoginListener

CHANGELOG.md, src/FOM/UserBundle/Security/Permission/YamlApplicationVoter.php, src/Mapbender/CoreBundle/Component/ApplicationYAMLMapper.php, src/Mapbender/WmsBundle/Component/WmsCapabilitiesParser130.php, src/Mapbender/WmsBundle/Entity/WmsInstanceLayer.php
A YAML application was only hidden from public view if the `published` key was not present at all, `published: false` was interpreted like `published: true`. This PR fixes this behaviour.
=> [Security] Fix `published: false` was ignored in YAML applications

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapEngineOl4.js
The problem occurred in the mapbender_user demo. The map element was set to EPSG:3857 and worldwide maximum bounds (`[ -20037508.34278924, -20037508.34278924, 20037508.34278924, 20037508.34278924 ]`). OpenLayers transformed that into EPSG:25832 (UTM32) with `[ 586331.6298902088, -10543719.766426057, 586331.6298902095, 10543719.766426057 ]`, which is technically not wrong (-180° W is the same point on earth as 180° E), but still messed up the maximum extent calculation.
The workaround is now to check if max x / min x used to be -1 and is 1 after the transformation, in that case the sign is changed.
fixes #1602
=> [Map] Transformation failed in some cases when EPSG:3847 is transformed into UTM coordinates

CHANGELOG.md, docs/elements/elements.md, src/Mapbender/CoreBundle/Component/ElementBase/ValidatableConfigurationInterface.php, src/Mapbender/CoreBundle/Component/Presenter/Application/ConfigService.php, src/Mapbender/CoreBundle/Element/Map.php, src/Mapbender/CoreBundle/Resources/config/services.xml, src/Mapbender/CoreBundle/Resources/public/mapbender.application.js, src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml, src/Mapbender/ManagerBundle/Controller/ElementController.php, src/Mapbender/ManagerBundle/Resources/config/controllers.xml
An interface `Mapbender\CoreBundle\Component\ElementBase\ValidatableConfigurationInterface` with the method `validate` was added. This enables an element to validate its configuration, e.g. to check that the minimum extent is smaller than the maximum extent in the map element. 
The method is called in two cases:
- when saving a form in the administration backend. The `$form` attribute will be non-null. You should create a form error in this case, e.g. `$form->get('configuration')->get('mykey')->addError(new FormError('Something went wrong'));` 
Example of the error display:
- when accessing an application in the frontend. In this case, the `$form` argument will be null. This also allows YAML-defined applications to be checked. Throw a …
=> Add ValidatableConfigurationInterface to validate an element's configuration

CHANGELOG.md, src/FOM/UserBundle/Entity/Permission.php
Rename field fom_permission.resource to fom.permission.resource-ref to prevent oracledb reserved word issues
=> Fix compatibility with OracleDB

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js, src/Mapbender/MobileBundle/Resources/public/sass/theme/mobile.scss
refs #1617
Solution: Replaced margin on the left hand side of the layer tree by padding. On the left hand side (20px wide), scrolling is now possible while the rest of the row still allows for reordering layers.
=> [Mobile Template] Allow scrolling layer tree on the left edge

CHANGELOG.md, docs/gitarchive/gitarchive.md, src/Mapbender/CoreBundle/Asset/ApplicationAssetOverrides.php, src/Mapbender/CoreBundle/Asset/ApplicationAssetService.php, src/Mapbender/CoreBundle/Resources/config/services.xml
Problem was, that the request stack is not yet initialised when booting the bundle. However, through many interdependencies, the PathPackage was required in the ApplicationAssetService initialising the basePath to empty string.
Solution: Do not inject the ApplicationAssetService service when registrering overrides in the bundle, but a standalone new service ApplicationAssetOverrides, that does not have any dependencies and therefore also does not trigger the PathPackage to be initialised.
:warning: Any application already using asset overriding needs to be changed:
When injecting the service: `mapbender.application_asset.service` -> `mapbender.application_asset.overrides.service`
When using the class directly: `Mapbender\CoreBundle\Asset\ApplicationAssetService` -> …
=> Move asset overriding to its own service to avoid request stack problems

CHANGELOG.md, src/Mapbender/CoreBundle/Controller/ElementController.php
=> Fix ajax requests fail in YAML applications (regression introduced in 4.0.1)

CHANGELOG.md, docs/UPGRADING.md, docs/sources/sources.md, src/Mapbender/CoreBundle/Element/Layertree.php, src/Mapbender/CoreBundle/Element/Legend.php, src/Mapbender/CoreBundle/Element/Type/LayerTreeMenuType.php, src/Mapbender/CoreBundle/Element/Type/LayertreeAdminType.php, src/Mapbender/CoreBundle/Resources/public/element/LegendEntry.js, src/Mapbender/CoreBundle/Resources/public/element/resetView.js, src/Mapbender/CoreBundle/Resources/public/mapbender-model/MapModelBase.js, src/Mapbender/CoreBundle/Resources/public/mapbender-model/source.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.layertree.tree.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.legend.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js, src/Mapbender/CoreBundle/Resources/public/mapbender.geosource.js, src/Mapbender/CoreBundle/Resources/public/sass/element/legend.scss, src/Mapbender/CoreBundle/Resources/views/Element/layertree.html.twig, src/Mapbender/FrameworkBundle/Component/UserInfoProvider.php, src/Mapbender/PrintBundle/Component/CanvasLegend.php, src/Mapbender/PrintBundle/Component/LegendHandler.php, src/Mapbender/PrintBundle/Element/PrintClient.php, src/Mapbender/PrintBundle/Resources/config/services.xml, src/Mapbender/PrintBundle/Resources/public/element/printclient.js, src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js, src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js, src/Mapbender/WmtsBundle/Resources/public/geosource-base.js, src/Mapbender/WmtsBundle/Resources/public/mapbender.geosource.tms.js
Sources now use native ES6 classes instead of prototype pseudo-classes. This means, for custom sources, you
must also use this syntax now. Refer to the [new docs entry](sources/sources.md) for details.
The following has changed apart from the class syntax:
- several methods that were already present in the WMSSource have been moved to the abstract Mapbender.Source
- new event `mbmapsourcelayersreordered` that fires when the layer order within a source is moved. In earlier versions, `mbmapsourcemoved` was called then.
- `Mapbender.Source.wmsloader` renamed to `Mapbender.Source.isDynamicSource`
A layer's legend can now also be a style definition instead of a plain url. If you handle legend urls, adapt accordingly (see [documentation]((sources/sources.md)) for new syntax):
- In …
=> Frontend source refactoring

src/Mapbender/CoreBundle/Form/Type/InstanceLayerStyleChoiceType.php, src/Mapbender/CoreBundle/Resources/public/mapbender-model/source.js, src/Mapbender/CoreBundle/Resources/public/sass/modules/_input.scss, src/Mapbender/CoreBundle/Resources/public/widgets/dropdown.js, src/Mapbender/WmsBundle/Form/EventListener/FieldSubscriber.php, src/Mapbender/WmsBundle/Resources/translations/messages.de.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.en.yaml
follow-up PR to #1636 
Mapbender requests styles only for individual layers, not for groups. Switching the style for groups was possible before but had no effect. This PR disables switching the style for groups (both backend and frontend) and shows a message on hover in the backend that switching styles in only possible on leaf level.
=> Do not offer style selection for groups

src/Mapbender/PrintBundle/Component/Legend/LegendBlock.php, src/Mapbender/PrintBundle/Component/LegendHandler.php, src/Mapbender/PrintBundle/Component/PDF_Extensions.php, src/Mapbender/PrintBundle/Component/TemplateRegion.php, src/Mapbender/PrintBundle/Component/Transport/ImageTransport.php
This is mostly improving developer experience. The measuring of a legend block (title, image and overall width/height) and the actual PDF rendering are separated. This was implemented for a client project, where the legend should only be printed on the map page if it fits on the page entirely.
The title width calculation now respects the page margins.
Left: before, right: after
Until now, the default margins were very big, creating a huge unnecessary amount of whitespace on the legend page. This was reduced.
Left: before, right: after
If a single legend graphic was too big even if it's the only image in  a column it was cropped off. Now, it gets scaled down to fit on the page.
Left: before, right: after
Column widths in the legend were fixed until now (variable `$maxColumnWidthMm` within …
=> [PrintClient] Various improvements in LegendHandler 

CHANGELOG.md, src/Mapbender/WmtsBundle/Resources/public/mapbender.geosource.wmts.js
Pass WMTS tile size to TileGrid constructor (default tile size of 256px was assumed)
=> Fix WMTS sources with tile size other than 256px were not rendered correctly

CHANGELOG.md, src/Mapbender/CoreBundle/Element/FeatureInfo.php, src/Mapbender/CoreBundle/Element/Type/FeatureInfoAdminType.php, src/Mapbender/CoreBundle/Resources/public/element/featureinfo-highlighting.js, src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js
In addition to data-geometry and data-srid the new attribute data-label is read from a feature in the feature info html (QGIS: maptip). 
It can be styled using the new options 
- `fontColorDefault` (default: #000000)
- `fontColorHover` (default: #000000)
- `fontSizeDefault` (default: 12)
- `fontSizeHover` (default: 12)
see internal ticket 7433
=> Support data-label attribute in feature info highlighting

CHANGELOG.md, src/Mapbender/CoreBundle/Entity/SourceInstance.php, src/Mapbender/WmsBundle/Component/Presenter/WmsSourceService.php
For protected WMS, the basic auth data was not added to GetLegendGraphic requests, since the legend urls is loaded directly from the Capabilities and there, the basic auth data is of course not added. 
This PR manually adds the basic auth data to the legend urls by injecting them afterwards.
see internal ticket 8930
=> [WmsLoader] Add basic auth to legend urls for protected WMS

CHANGELOG.md, src/Mapbender/CoreBundle/Component/SQLSearchEngine.php
Per default, the map extent is now compared to a feature by converting both to EPSG:4326 (WGS84).
Comparing in a non-global SRS (like UTM32) can result in errors when comparing it to an extent defined in a global CRS. This may reduce performance, so the transformation to EPSG:4326 can be disabled by passing `noTransform:true` to `class_options`.
see internal ticket 9356
=> [SearchRouter] Compare extents to features in EPSG:4326 only

src/Mapbender/RoutingBundle/Component/RoutingDriver/OsrmDriver.php, src/Mapbender/RoutingBundle/Component/SearchDriver/SolrDriver.php, src/Mapbender/RoutingBundle/Resources/public/mapbender.element.routing.js
This pull request fixes ...
- ... the usage of different transport types - such as car, bike, foot - for the OSRM-Search
- ... the usage of german umlaut in the solr search 
It also adds support for nested placeholders to access the response object of the solr search, e.g. `${nested.attribute.path}`
=> Fix transport type and Solr-Search

src/Mapbender/ManagerBundle/Controller/ElementController.php
This error occurs when an element is deleted in an application. The order of the elements is then changed in ALL other applications.
The only thing missing was a where clause for the current application.
see also internal ticket 9071
=> Fix order of elements in application config

src/Mapbender/CoreBundle/Resources/public/sass/modules/jqueryui_minimal.scss
Fixes the jqueryui class 'ui-helper-hidden-accessible'. 
Currently the div element with this class is not really hidden.
Steps to reproduce:
- open app with a simple search element
- deactivate background layer
- use the search
-> results are displayed in the top left corner (maybe behind the toolbar)
internal ticket: 9825
=> Fix jqueryui hidden-accessible class

CHANGELOG.md, docs/security/permission-system.md, src/FOM/UserBundle/Controller/PermissionController.php, src/FOM/UserBundle/Controller/SecurityController.php, src/FOM/UserBundle/Resources/config/controllers.xml, src/FOM/UserBundle/Resources/config/services.xml, src/FOM/UserBundle/Resources/views/Group/list.html.twig, src/FOM/UserBundle/Security/Permission/GlobalPermissionProvider.php, src/FOM/UserBundle/Security/Permission/ResourceDomainInstallation.php, src/Mapbender/FrameworkBundle/DependencyInjection/Compiler/RegisterGlobalPermissionDomainsPass.php, src/Mapbender/FrameworkBundle/MapbenderFrameworkBundle.php
If you want to add an installation-wide permission that is not dependent on a single resource, create a class implementing the `FOM\UserBundle\Security\Permission\GlobalPermissionProvider` interface and tag it with `fom.security.global_permission`.
The interface has two methods that need to implemented:
- `getCategories()`: Returns the permission categories you want to add to the list that appears when navigating to Security / Global Permissions.
can be left empty if you only want to extend a category that already exists.  
The keys should be unique string aliases for the category, the values translation keys for the human-readable values.
- `getPermissions()`: Returns the actual permissions you want to add. The keys are unique (unique across all categories!) string aliases,
the values …
=> [Security] Make global permission extendable

CHANGELOG.md, src/Mapbender/ApiBundle/Controller/CommandController.php, src/Mapbender/ManagerBundle/Controller/SourceInstanceController.php, src/Mapbender/WmsBundle/Command/SourceAssignCommand.php
- Adds new options to the mapbender:wms:assign command and the  /api/wms/assign api-request 
- see internal #10243
New options are
- --format
- --infoformat
- --proxy
- --tiled
- --layerorder
get information via
`bin/console mapbender:wms:assign --help`
=> [ApiBundle] Add new options for wms:assign

src/Mapbender/RoutingBundle/Resources/public/mapbender.element.routing.js
Fixes no route and marker displayed when search is repeated. -> Happens when routing is configured in the popup-dialog.
see internal issue #10311
=> [Routing] Fix routing in popup-dialog

src/Mapbender/ApiBundle/Controller/CommandController.php
Another small fix here, because we cannot (always) use the console command's exit code as the controller's response code. This only works if the console command returns 404, which happens in some cases.
=> [API] Fix controller response status code

src/Mapbender/WmsBundle/Component/Presenter/WmsSourceService.php
WMS that dont have a LegendURL in their style definition prevent the application from starting when they are loaded via the OWSProxy. 
Solution: we skip the proxifyUrl function for these WMS
see internal ticket 10701 for example WMS
=> Fix app config when using WMS without legendUrl via proxy

CHANGELOG.md, src/Mapbender/ManagerBundle/Component/ExportHandler.php, src/Mapbender/WmsBundle/Component/Wms/SourceInstanceFactory.php, src/Mapbender/WmtsBundle/Component/InstanceFactoryCommon.php, src/Mapbender/WmtsBundle/Entity/HttpTileSource.php, src/Mapbender/WmtsBundle/Entity/TileMatrixSet.php, src/Mapbender/WmtsBundle/Resources/config/services.xml, src/Mapbender/WmtsBundle/Resources/public/geosource-base.js
So far, only WMS sources could be configured in YAML applications. Along with VectorTiles sources introduced in version 4.2, this PR also enables WMTS and TMS sources to be configured using YAML.
It supports the following fields:
- `type`: must be __wmts__ or __tms__
- `url`: URL to the service's Get capability XML. Note that to obtain the TileMatrices this document will be downloaded for every page view (unlike for database WMTS sources, where this information is cached in the database)
- `title`: The source title as displayed in the layer tree
- `basesource` (alias: `isBaseSource`): boolean value if the source should be treated as a base source
- `opacity`: int 0 (fully transparent)-100 (fully opaque) 
- `selected` (alias: `visible`): initial selected state of the root layer. (default: …
=> Support definition of WMTS/TMS sources in YAML

CHANGELOG.md, src/Mapbender/WmsBundle/Component/Presenter/WmsSourceInstanceConfigGenerator.php, src/Mapbender/WmsBundle/Component/Wms/SourceInstanceFactory.php, src/Mapbender/WmsBundle/Entity/WmsInstance.php, src/Mapbender/WmsBundle/Form/Type/WmsInstanceInstanceLayersType.php, src/Mapbender/WmsBundle/Resources/config/services.xml, src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js, src/Mapbender/WmsBundle/Resources/translations/messages.de.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.en.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.es.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.fr.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.it.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.nl.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.pt.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.ru.yaml, src/Mapbender/WmsBundle/Resources/translations/messages.uk.yaml, src/Mapbender/WmsBundle/Resources/views/Repository/instance.html.twig
Adds an option to refresh a WMS services automatically after a set number of seconds. Can be used e.g. for WMS services that visualise sensor data.
Configuration in backend: Enter a non-zero value in the new backend field:
Configuration in YAML: use the property `refreshInterval` in the source configuration.
=>  Implement auto refresh functionality for wms 

CHANGELOG.md, src/Mapbender/WmsBundle/Component/Presenter/WmsSourceInstanceConfigGenerator.php
Regression introduced by #1744 
fixes #1772
=> [WMS] Fix layer order in frontend was wrong after updating instance layer properties

CHANGELOG.md, src/Mapbender/CoreBundle/Resources/public/element/sketch.js, src/Mapbender/CoreBundle/Resources/public/element/sketch.scss, src/Mapbender/CoreBundle/Resources/translations/messages.de.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.en.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.es.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.fr.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.it.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.nl.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.pt.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.ru.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.tr.yaml, src/Mapbender/CoreBundle/Resources/translations/messages.uk.yaml, src/Mapbender/CoreBundle/Resources/views/Element/sketch.html.twig
- in pop-up: Close button has been removed and replaced with an “x” in the top right corner
- in the “Radius” field, the “m” has been removed (replaced with Radius (m))
- text fields are flush
- the label for a single-line field is now above the input field, not to the left of it
=> [Design] sketches (sidepane), internal ticket 10677
